import ShenWork.Paper1.WholeLineChiPosDispersion
import ShenWork.Paper1.Statements

/-!
# The resolvent multiplier bound behind the dispersion relation

The dispersion relation `λ(k) = −α − k² + χγ·k²/(1+k²)` proved in
`WholeLineChiPosDispersion.lean` has the factor `χγ`, in which the `γ` comes
from linearizing `u^γ` at `u ≡ 1` and the resolvent
`v = (1 − ∂xx)^{-1}[u^γ]` contributes the multiplier `1/(1+k²) ∈ (0, 1]`.

This file ties the abstract spectral gap to the ACTUAL nonlocal operator of the
system: the frozen elliptic solve `frozenElliptic p` (= `Psi (u^γ) 1 1`).  Two
facts are what the linearized-stability argument consumes:

* at the equilibrium the resolvent is the identity on constants:
  `frozenElliptic p (fun _ => 1) x = 1` (the `k = 0` multiplier value, its
  maximum), and
* the resolvent is order-preserving between `0` and `1`, so a datum trapped in
  `[0, 1]` has its signal trapped in `[0, 1]` — the `L^∞` contraction that the
  multiplier bound `1/(1+k²) ≤ 1` expresses in physical space.
-/

open Real

noncomputable section

namespace ShenWork.Paper1

/-- At the constant equilibrium `u ≡ 1` the frozen elliptic solve returns `1`:
this is the `k = 0` value of the resolvent multiplier `1/(1+k²)`, its maximum. -/
theorem frozenElliptic_one : frozenElliptic p (fun _ : ℝ => 1) = fun _ => 1 := by
  funext x
  unfold frozenElliptic
  simp only [one_rpow]
  exact Psi_const (le_refl (0:ℝ) |>.trans zero_le_one) x

/-- The physical-space form of the multiplier bound `1/(1+k²) ≤ 1`: a signal
generated by a datum bounded by `1` is itself bounded by `1`.  (Order-preserving
resolvent — the `L^∞` contraction.) -/
theorem frozenElliptic_le_one_of_datum_le_one
    {u : ℝ → ℝ} (hu0 : ∀ x, 0 ≤ u x) (hu1 : ∀ x, u x ≤ 1) (x : ℝ) :
    frozenElliptic p u x ≤ 1 :=
  frozenElliptic_le_one_of_le_one p hu0 hu1 x

/-- The multiplier is nonnegative in physical space: a nonnegative datum yields a
nonnegative signal. -/
theorem frozenElliptic_nonneg_of_datum_nonneg
    {u : ℝ → ℝ} (hu : ∀ x, 0 ≤ u x) (x : ℝ) :
    0 ≤ frozenElliptic p u x :=
  frozenElliptic_nonneg p hu x

/-- Assembled spectral picture at `u ≡ 1`: with the resolvent identity on the
equilibrium (`frozenElliptic 1 = 1`, the maximal multiplier), the dispersion
relation `λ(k) = −α − k² + χγ·k²/(1+k²)` has, for `χγ ≤ 1`, a uniform spectral
gap `α`.  This is the analytic statement that the disputed window `[1/2, χ*)` of
Theorem 1.2 is linearly stable: `χ* ≤ 1`, so `χγ ≤ γ`, and at `γ = 1` the gap
condition `χγ ≤ 1` is exactly `χ ≤ 1`. -/
theorem chiPos_linear_stability_at_equilibrium
    (p : CMParams) (hχ0 : 0 ≤ p.χ) (hχγ : p.χ * p.γ ≤ 1) {s : ℝ} (hs : 0 ≤ s) :
    dispersion p.α (p.χ * p.γ) s ≤ -p.α :=
  dispersion_le_neg_alpha p.α (p.χ * p.γ)
    (mul_nonneg hχ0 (le_trans zero_le_one p.hγ)) hχγ hs

section AxiomAudit

#print axioms frozenElliptic_one
#print axioms frozenElliptic_le_one_of_datum_le_one
#print axioms chiPos_linear_stability_at_equilibrium

end AxiomAudit

end ShenWork.Paper1
