import ShenWork.Paper1.WholeLineWeightedRegularityGeneratorRestartNatural
import ShenWork.Paper1.WholeLineWeightedRegularitySemigroupTimeModulus
import Mathlib.Analysis.SpecialFunctions.Integrals.Basic

open Filter MeasureTheory Set Topology
open scoped RealInnerProductSpace Interval

noncomputable section

namespace ShenWork.Paper1

/-!
# Quantitative time modulus for exact-weight heat Duhamel histories

The zero-lag heat family is only strongly continuous.  An interior Duhamel
history nevertheless has a quantitative modulus: split off a recent time
strip, and use the positive-lag generator estimate on the older history.
The resulting `h * log (H / h)` term is bounded by a square-root modulus.
-/

/-- The elementary logarithmic loss generated by the far Duhamel history is
bounded by a square-root modulus. -/
theorem mul_log_div_le_two_sqrt_mul_sqrt
    {H h : ℝ} (hH : 0 < H) (hh : 0 < h) (_hhH : h ≤ H) :
    h * Real.log (H / h) ≤ 2 * Real.sqrt H * Real.sqrt h := by
  have hratio : 0 ≤ H / h := div_nonneg hH.le hh.le
  have hlog := Real.log_le_rpow_div hratio
    (show 0 < (1 / 2 : ℝ) by norm_num)
  rw [← Real.sqrt_eq_rpow, Real.sqrt_div hH.le] at hlog
  have hsqrth : 0 < Real.sqrt h := Real.sqrt_pos.2 hh
  calc
    h * Real.log (H / h) ≤
        h * ((Real.sqrt H / Real.sqrt h) / (1 / 2 : ℝ)) :=
      mul_le_mul_of_nonneg_left hlog hh.le
    _ = 2 * Real.sqrt H * Real.sqrt h := by
      field_simp [ne_of_gt hsqrth]
      rw [Real.sq_sqrt hh.le]

/-- Exact inverse-lag mass on the far part of a recent-window split. -/
theorem intervalIntegral_inv_sub_eq_log_div
    {a s h : ℝ} (hh : 0 < h) (ham : a ≤ s - h) :
    (∫ q in a..s - h, (s - q)⁻¹) = Real.log ((s - a) / h) := by
  rw [intervalIntegral.integral_comp_sub_left]
  have hsa : 0 < s - a := hh.trans_le (by linarith)
  rw [show s - (s - h) = h by ring, integral_inv_of_pos hh hsa]

/-- A constant pointwise norm bound gives the sharp interval-length bound
for a Bochner interval integral. -/
theorem intervalIntegral_norm_le_const_mul_sub
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {a b C : ℝ} (hab : a ≤ b) {G : ℝ → E}
    (hG : ∀ q ∈ Set.Icc a b, ‖G q‖ ≤ C) :
    ‖∫ q in a..b, G q‖ ≤ C * (b - a) := by
  have hraw := intervalIntegral.norm_integral_le_of_norm_le_const
    (f := G) (C := C) (a := a) (b := b) (fun q hq => by
      apply hG q
      rw [Set.uIoc_of_le hab] at hq
      exact ⟨hq.1.le, hq.2⟩)
  simpa only [abs_of_nonneg (sub_nonneg.mpr hab)] using hraw

/-- Integrating an inverse-lag majorant on the far history produces the
exact logarithmic factor. -/
theorem intervalIntegral_norm_le_const_mul_log_div
    {E : Type*} [NormedAddCommGroup E] [NormedSpace ℝ E]
    {a s h C : ℝ} (hh : 0 < h) (ham : a ≤ s - h)
    {G : ℝ → E}
    (hGint : IntervalIntegrable G volume a (s - h))
    (hG : ∀ q ∈ Set.Icc a (s - h), ‖G q‖ ≤ C * (s - q)⁻¹) :
    ‖∫ q in a..s - h, G q‖ ≤ C * Real.log ((s - a) / h) := by
  have hinv : IntervalIntegrable (fun q : ℝ => (s - q)⁻¹)
      volume a (s - h) := by
    apply intervalIntegral.intervalIntegrable_inv
    · intro q hq
      rw [Set.uIcc_of_le ham] at hq
      have : 0 < s - q := hh.trans_le (by linarith [hq.2])
      exact ne_of_gt this
    · exact (continuous_const.sub continuous_id).continuousOn
  have hmajor : IntervalIntegrable (fun q : ℝ => C * (s - q)⁻¹)
      volume a (s - h) := hinv.const_mul C
  calc
    ‖∫ q in a..s - h, G q‖ ≤ ∫ q in a..s - h, ‖G q‖ :=
      intervalIntegral.norm_integral_le_integral_norm ham
    _ ≤ ∫ q in a..s - h, C * (s - q)⁻¹ :=
      intervalIntegral.integral_mono_on ham hGint.norm hmajor hG
    _ = C * ∫ q in a..s - h, (s - q)⁻¹ := by
      rw [intervalIntegral.integral_const_mul]
    _ = C * Real.log ((s - a) / h) := by
      rw [intervalIntegral_inv_sub_eq_log_div hh ham]

/-- Near/far decomposition for two values of one exact-weight heat Duhamel
history.  The recent strips have length `h = t - s`; the old history pays
only the logarithmic positive-lag loss. -/
theorem weightedMovingHeatL2Semigroup_duhamel_sub_norm_le_log
    {eta c a R s t K : ℝ}
    (haR : a < R) (_hK : 0 ≤ K)
    (has : a ≤ s) (hst : s ≤ t) (htR : t ≤ R)
    (hstep : 0 < t - s) (hfar : a ≤ s - (t - s))
    {F : ℝ → WholeLineRealL2}
    (hF : ∀ q ∈ Set.Icc a R, ‖F q‖ ≤ K)
    (hTint : IntervalIntegrable
      (fun q => weightedMovingHeatL2Semigroup eta c (t - q) (F q))
      volume a t)
    (hSint : IntervalIntegrable
      (fun q => weightedMovingHeatL2Semigroup eta c (s - q) (F q))
      volume a s) :
    ‖(∫ q in a..t,
          weightedMovingHeatL2Semigroup eta c (t - q) (F q)) -
        ∫ q in a..s,
          weightedMovingHeatL2Semigroup eta c (s - q) (F q)‖ ≤
      3 * Real.exp (|eta ^ 2 - c * eta| * (R - a)) * K * (t - s) +
        weightedMovingHeatGeneratorHorizonConst eta c (R - a) * K *
          (t - s) * Real.log ((s - a) / (t - s)) := by
  let h : ℝ := t - s
  let m : ℝ := s - h
  let A : ℝ := Real.exp (|eta ^ 2 - c * eta| * (R - a))
  let Cg : ℝ := weightedMovingHeatGeneratorHorizonConst eta c (R - a)
  let Tfun : ℝ → WholeLineRealL2 := fun q =>
    weightedMovingHeatL2Semigroup eta c (t - q) (F q)
  let Sfun : ℝ → WholeLineRealL2 := fun q =>
    weightedMovingHeatL2Semigroup eta c (s - q) (F q)
  let Old : ℝ → WholeLineRealL2 := fun q => Tfun q - Sfun q
  have hat : a ≤ t := has.trans hst
  have haRle : a ≤ R := haR.le
  have hsR : s ≤ R := hst.trans htR
  have hpos : 0 < h := by simpa only [h] using hstep
  have ham : a ≤ m := by simpa only [m, h] using hfar
  have hms : m ≤ s := sub_le_self _ hpos.le
  have htmem : t ∈ Set.Icc a R := ⟨hat, htR⟩
  have hsmem : s ∈ Set.Icc a R := ⟨has, hsR⟩
  have hT_as : IntervalIntegrable Tfun volume a s := by
    apply hTint.mono_set
    rw [Set.uIcc_of_le hat, Set.uIcc_of_le has]
    exact Set.Icc_subset_Icc_right hst
  have hT_st : IntervalIntegrable Tfun volume s t := by
    apply hTint.mono_set
    rw [Set.uIcc_of_le hat, Set.uIcc_of_le hst]
    exact Set.Icc_subset_Icc_left has
  have hOld : IntervalIntegrable Old volume a s := hT_as.sub hSint
  have hOld_far : IntervalIntegrable Old volume a m := by
    apply hOld.mono_set
    rw [Set.uIcc_of_le has, Set.uIcc_of_le ham]
    exact Set.Icc_subset_Icc_right hms
  have hOld_near : IntervalIntegrable Old volume m s := by
    apply hOld.mono_set
    rw [Set.uIcc_of_le has, Set.uIcc_of_le hms]
    exact Set.Icc_subset_Icc_left ham
  have hdecomp :
      (∫ q in a..t, Tfun q) - ∫ q in a..s, Sfun q =
        ((∫ q in a..m, Old q) + ∫ q in m..s, Old q) +
          ∫ q in s..t, Tfun q := by
    have hTsplit :=
      intervalIntegral.integral_add_adjacent_intervals hT_as hT_st
    have hOldSplit :=
      intervalIntegral.integral_add_adjacent_intervals hOld_far hOld_near
    rw [← hTsplit, hOldSplit,
      intervalIntegral.integral_sub hT_as hSint]
    abel
  have hnew_point : ∀ q ∈ Set.Icc s t, ‖Tfun q‖ ≤ A * K := by
    intro q hq
    have hqmem : q ∈ Set.Icc a R :=
      ⟨has.trans hq.1, hq.2.trans htR⟩
    calc
      ‖Tfun q‖ ≤ A * ‖F q‖ := by
        dsimp only [Tfun, A]
        exact weightedMovingHeatL2Semigroup_norm_apply_le_compact_lag
          haRle htmem hqmem (F q)
      _ ≤ A * K :=
        mul_le_mul_of_nonneg_left (hF q hqmem) (Real.exp_nonneg _)
  have hnew_bound : ‖∫ q in s..t, Tfun q‖ ≤ A * K * h := by
    simpa only [h] using
      intervalIntegral_norm_le_const_mul_sub hst hnew_point
  have hnear_point : ∀ q ∈ Set.Icc m s, ‖Old q‖ ≤ 2 * (A * K) := by
    intro q hq
    have hqmem : q ∈ Set.Icc a R :=
      ⟨ham.trans hq.1, hq.2.trans hsR⟩
    have htq : ‖Tfun q‖ ≤ A * K := by
      calc
        ‖Tfun q‖ ≤ A * ‖F q‖ := by
          dsimp only [Tfun, A]
          exact weightedMovingHeatL2Semigroup_norm_apply_le_compact_lag
            haRle htmem hqmem (F q)
        _ ≤ A * K :=
          mul_le_mul_of_nonneg_left (hF q hqmem) (Real.exp_nonneg _)
    have hsq : ‖Sfun q‖ ≤ A * K := by
      calc
        ‖Sfun q‖ ≤ A * ‖F q‖ := by
          dsimp only [Sfun, A]
          exact weightedMovingHeatL2Semigroup_norm_apply_le_compact_lag
            haRle hsmem hqmem (F q)
        _ ≤ A * K :=
          mul_le_mul_of_nonneg_left (hF q hqmem) (Real.exp_nonneg _)
    exact (norm_sub_le _ _).trans (by linarith)
  have hnear_bound : ‖∫ q in m..s, Old q‖ ≤ 2 * (A * K) * h := by
    have hraw := intervalIntegral_norm_le_const_mul_sub hms hnear_point
    simpa only [m, h, sub_sub_cancel] using hraw
  have hfar_point : ∀ q ∈ Set.Icc a m,
      ‖Old q‖ ≤ Cg * K * h * (s - q)⁻¹ := by
    intro q hq
    have hr : 0 < s - q := by
      have : h ≤ s - q := by dsimp only [m] at hq; linarith [hq.2]
      exact hpos.trans_le this
    have hh0 : 0 ≤ h := hpos.le
    have hrH : (s - q) + h ≤ R - a := by
      dsimp only [h]
      linarith [hq.1, htR]
    have hsem :=
      weightedMovingHeatL2Semigroup_sub_norm_le_of_positive_lag
        (eta := eta) (c := c) hr hh0 hrH (F q)
    have hqmem : q ∈ Set.Icc a R :=
      ⟨hq.1, hq.2.trans (hms.trans hsR)⟩
    calc
      ‖Old q‖ =
          ‖weightedMovingHeatL2Semigroup eta c ((s - q) + h) (F q) -
            weightedMovingHeatL2Semigroup eta c (s - q) (F q)‖ := by
        dsimp only [Old, Tfun, Sfun, h]
        congr 3
        ring
      _ ≤ (Cg * (s - q)⁻¹ * ‖F q‖) * h := by
        simpa only [Cg] using hsem
      _ ≤ (Cg * (s - q)⁻¹ * K) * h := by
        apply mul_le_mul_of_nonneg_right _ hpos.le
        apply mul_le_mul_of_nonneg_left (hF q hqmem)
        exact mul_nonneg
          (weightedMovingHeatGeneratorHorizonConst_nonneg
            (sub_nonneg.mpr haRle))
          (inv_nonneg.mpr hr.le)
      _ = Cg * K * h * (s - q)⁻¹ := by ring
  have hfar_bound : ‖∫ q in a..m, Old q‖ ≤
      Cg * K * h * Real.log ((s - a) / h) := by
    exact intervalIntegral_norm_le_const_mul_log_div hpos ham hOld_far hfar_point
  rw [show
      (∫ q in a..t,
          weightedMovingHeatL2Semigroup eta c (t - q) (F q)) -
        ∫ q in a..s,
          weightedMovingHeatL2Semigroup eta c (s - q) (F q) =
        (∫ q in a..t, Tfun q) - ∫ q in a..s, Sfun q by rfl,
    hdecomp]
  calc
    ‖((∫ q in a..m, Old q) + ∫ q in m..s, Old q) +
        ∫ q in s..t, Tfun q‖ ≤
      (‖∫ q in a..m, Old q‖ + ‖∫ q in m..s, Old q‖) +
          ‖∫ q in s..t, Tfun q‖ :=
      (norm_add_le _ _).trans (add_le_add (norm_add_le _ _) le_rfl)
    _ ≤ (Cg * K * h * Real.log ((s - a) / h) +
          2 * (A * K) * h) + A * K * h :=
      add_le_add (add_le_add hfar_bound hnear_bound) hnew_bound
    _ = 3 * Real.exp (|eta ^ 2 - c * eta| * (R - a)) * K *
          (t - s) +
        weightedMovingHeatGeneratorHorizonConst eta c (R - a) * K *
          (t - s) * Real.log ((s - a) / (t - s)) := by
      dsimp only [A, Cg, h]
      ring

/-- Square-root time modulus for an interior exact-weight Duhamel history.
The quantitative constant depends only on the ambient window, the semigroup
parameters, and the uniform forcing norm. -/
theorem weightedMovingHeatL2Semigroup_duhamel_sub_norm_le_sqrt
    {eta c a R s t delta K : ℝ}
    (hdelta : 0 < delta) (hK : 0 ≤ K)
    (hsInterior : a + delta ≤ s) (hst : s ≤ t) (htR : t ≤ R)
    (hstep : 0 < t - s)
    (hsmall : t - s ≤ min (delta / 2) 1)
    {F : ℝ → WholeLineRealL2}
    (hF : ∀ q ∈ Set.Icc a R, ‖F q‖ ≤ K)
    (hTint : IntervalIntegrable
      (fun q => weightedMovingHeatL2Semigroup eta c (t - q) (F q))
      volume a t)
    (hSint : IntervalIntegrable
      (fun q => weightedMovingHeatL2Semigroup eta c (s - q) (F q))
      volume a s) :
    ‖(∫ q in a..t,
          weightedMovingHeatL2Semigroup eta c (t - q) (F q)) -
        ∫ q in a..s,
          weightedMovingHeatL2Semigroup eta c (s - q) (F q)‖ ≤
      (3 * Real.exp (|eta ^ 2 - c * eta| * (R - a)) * K +
        2 * weightedMovingHeatGeneratorHorizonConst eta c (R - a) * K *
          Real.sqrt (R - a)) * Real.sqrt (t - s) := by
  have has : a ≤ s := by linarith
  have haR : a < R := by linarith [hst, htR]
  have hfar : a ≤ s - (t - s) := by
    have hhalf : t - s ≤ delta / 2 := hsmall.trans (min_le_left _ _)
    linarith
  have hlog := weightedMovingHeatL2Semigroup_duhamel_sub_norm_le_log
    (eta := eta) (c := c) haR hK has hst htR hstep hfar hF hTint hSint
  have hH : 0 < R - a := sub_pos.mpr haR
  have hsa : 0 < s - a := by linarith
  have hhsa : t - s ≤ s - a := by linarith
  have hlogsqrt0 := mul_log_div_le_two_sqrt_mul_sqrt
    hsa hstep hhsa
  have hsqrtle : Real.sqrt (s - a) ≤ Real.sqrt (R - a) :=
    Real.sqrt_le_sqrt (by linarith)
  have hlogsqrt :
      (t - s) * Real.log ((s - a) / (t - s)) ≤
        2 * Real.sqrt (R - a) * Real.sqrt (t - s) :=
    hlogsqrt0.trans (by
      exact mul_le_mul_of_nonneg_right
        (mul_le_mul_of_nonneg_left hsqrtle (by norm_num : (0 : ℝ) ≤ 2))
        (Real.sqrt_nonneg _))
  have hstep_one : t - s ≤ 1 := hsmall.trans (min_le_right _ _)
  have hle_sqrt : t - s ≤ Real.sqrt (t - s) := by
    rw [Real.le_sqrt' hstep]
    nlinarith
  have hA0 : 0 ≤ Real.exp (|eta ^ 2 - c * eta| * (R - a)) :=
    Real.exp_nonneg _
  have hCg0 :
      0 ≤ weightedMovingHeatGeneratorHorizonConst eta c (R - a) :=
    weightedMovingHeatGeneratorHorizonConst_nonneg hH.le
  calc
    ‖(∫ q in a..t,
          weightedMovingHeatL2Semigroup eta c (t - q) (F q)) -
        ∫ q in a..s,
          weightedMovingHeatL2Semigroup eta c (s - q) (F q)‖ ≤
      3 * Real.exp (|eta ^ 2 - c * eta| * (R - a)) * K * (t - s) +
        weightedMovingHeatGeneratorHorizonConst eta c (R - a) * K *
          ((t - s) * Real.log ((s - a) / (t - s))) := by
      simpa only [mul_assoc] using hlog
    _ ≤ 3 * Real.exp (|eta ^ 2 - c * eta| * (R - a)) * K *
          Real.sqrt (t - s) +
        weightedMovingHeatGeneratorHorizonConst eta c (R - a) * K *
          (2 * Real.sqrt (R - a) * Real.sqrt (t - s)) := by
      apply add_le_add
      · exact mul_le_mul_of_nonneg_left hle_sqrt
          (mul_nonneg (mul_nonneg (by positivity) hA0) hK)
      · exact mul_le_mul_of_nonneg_left hlogsqrt (mul_nonneg hCg0 hK)
    _ = (3 * Real.exp (|eta ^ 2 - c * eta| * (R - a)) * K +
          2 * weightedMovingHeatGeneratorHorizonConst eta c (R - a) * K *
            Real.sqrt (R - a)) * Real.sqrt (t - s) := by ring

/-- Measurable-history form of the interior square-root estimate.  Both
Bochner interval-integrability premises are generated from the ambient
history measurability and the single uniform forcing bound. -/
theorem weightedMovingHeatL2Semigroup_duhamel_sub_norm_le_sqrt_of_history_measurable
    {eta c a R s t delta K : ℝ}
    (hdelta : 0 < delta) (hK : 0 ≤ K)
    (hsInterior : a + delta ≤ s) (hst : s ≤ t) (htR : t ≤ R)
    (hstep : 0 < t - s)
    (hsmall : t - s ≤ min (delta / 2) 1)
    {F : ℝ → WholeLineRealL2}
    (hF : ∀ q ∈ Set.Icc a R, ‖F q‖ ≤ K)
    (hhist_meas : ∀ r : ℝ, AEStronglyMeasurable
      (fun q => weightedMovingHeatL2Semigroup eta c (r - q) (F q))
      (volume.restrict (Set.Icc a R))) :
    ‖(∫ q in a..t,
          weightedMovingHeatL2Semigroup eta c (t - q) (F q)) -
        ∫ q in a..s,
          weightedMovingHeatL2Semigroup eta c (s - q) (F q)‖ ≤
      (3 * Real.exp (|eta ^ 2 - c * eta| * (R - a)) * K +
        2 * weightedMovingHeatGeneratorHorizonConst eta c (R - a) * K *
          Real.sqrt (R - a)) * Real.sqrt (t - s) := by
  have has : a ≤ s := by linarith
  have hat : a ≤ t := has.trans hst
  have hsR : s ≤ R := hst.trans htR
  have hTint : IntervalIntegrable
      (fun q => weightedMovingHeatL2Semigroup eta c (t - q) (F q))
      volume a t := by
    apply weightedMovingHeatL2Semigroup_intervalIntegrable_of_uniform_norm_bound
      hat hK
    · intro q hq
      exact hF q ⟨hq.1, hq.2.trans htR⟩
    · apply (hhist_meas t).mono_measure
      exact Measure.restrict_mono (Set.Icc_subset_Icc_right htR) le_rfl
  have hSint : IntervalIntegrable
      (fun q => weightedMovingHeatL2Semigroup eta c (s - q) (F q))
      volume a s := by
    apply weightedMovingHeatL2Semigroup_intervalIntegrable_of_uniform_norm_bound
      has hK
    · intro q hq
      exact hF q ⟨hq.1, hq.2.trans hsR⟩
    · apply (hhist_meas s).mono_measure
      exact Measure.restrict_mono (Set.Icc_subset_Icc_right hsR) le_rfl
  exact weightedMovingHeatL2Semigroup_duhamel_sub_norm_le_sqrt
    hdelta hK hsInterior hst htR hstep hsmall hF hTint hSint

section AxiomAudit

#print axioms mul_log_div_le_two_sqrt_mul_sqrt
#print axioms intervalIntegral_inv_sub_eq_log_div
#print axioms intervalIntegral_norm_le_const_mul_sub
#print axioms intervalIntegral_norm_le_const_mul_log_div
#print axioms weightedMovingHeatL2Semigroup_duhamel_sub_norm_le_log
#print axioms weightedMovingHeatL2Semigroup_duhamel_sub_norm_le_sqrt
#print axioms
  weightedMovingHeatL2Semigroup_duhamel_sub_norm_le_sqrt_of_history_measurable

end AxiomAudit

end ShenWork.Paper1
