import ShenWork.Paper1.WholeLineCauchyLocalExistence
import ShenWork.PDE.IntervalFullKernelSDependentMeasurable
import ShenWork.PDE.IntervalGradDuhamelBound

open Filter Topology MeasureTheory Real Set
open scoped Topology
open intervalIntegral

noncomputable section

namespace ShenWork.Paper1

/-!
# The faithful whole-line Cauchy Duhamel map

The existing `PaperOne.wholeLineHeatOp` is the semigroup generated by
`Δ - I`.  Consequently the source paired with it must be

`u + u(1-u^α) = u(2-u^α)`.

Using only `u(1-u^α)` there loses the linear growth term of the paper's PDE.
This file defines the corrected source and uses the already proved bounded-
input Gaussian gradient operator for the divergence-form chemotaxis leg.
-/

/-! ## Root-compatible bounded-input heat operators

The analogous `PaperOne` files currently collide with an older root-imported
name.  These small definitions live on the common `PDE.HeatSemigroup` layer,
so the actual Cauchy producer remains importable from `ShenWork.lean`.
-/

/-- The modified whole-line heat operator generated by `Δ-I`. -/
def wholeLineCauchyHeatOp (t : ℝ) (f : ℝ → ℝ) (x : ℝ) : ℝ :=
  modifiedSemigroup t f x

/-- Bounded-input spatial-gradient heat operator in kernel form. -/
def wholeLineCauchyHeatGradOp (t : ℝ) (f : ℝ → ℝ) (x : ℝ) : ℝ :=
  ∫ y : ℝ, Real.exp (-t) *
    (deriv (fun z : ℝ => heatKernel t (z - y)) x * f y)

/-- Interval-integral gradient Duhamel operator. -/
def wholeLineCauchyGradientDuhamel
    (F : ℝ → ℝ → ℝ) (t x : ℝ) : ℝ :=
  ∫ s in (0 : ℝ)..t, wholeLineCauchyHeatGradOp (t - s) (F s) x

/-- Set-integral value Duhamel operator. -/
def wholeLineCauchyValueDuhamel
    (F : ℝ → ℝ → ℝ) (t x : ℝ) : ℝ :=
  ∫ s in Set.Icc (0 : ℝ) t, wholeLineCauchyHeatOp (t - s) (F s) x

theorem wholeLineCauchyHeatGradOp_abs_le
    {f : ℝ → ℝ} {M t : ℝ}
    (ht : 0 < t) (hM : 0 ≤ M) (hf : ∀ y, |f y| ≤ M) (x : ℝ) :
    |wholeLineCauchyHeatGradOp t f x| ≤
      Real.exp (-t) * ((2 / Real.sqrt (4 * Real.pi * t)) * M) := by
  simpa [wholeLineCauchyHeatGradOp] using
    modifiedHeatKernel_deriv_convolution_bounded_abs_le
      (t := t) (M := M) ht hM (f := f) hf x

lemma two_div_sqrt_four_pi_mul_eq_rpow_cauchy
    {τ : ℝ} (hτ : 0 < τ) :
    2 / Real.sqrt (4 * Real.pi * τ) =
      (2 / Real.sqrt (4 * Real.pi)) * τ ^ (-(1 / 2 : ℝ)) := by
  have h4pi : 0 < 4 * Real.pi := by positivity
  have hsqrt4pi : Real.sqrt (4 * Real.pi) ≠ 0 :=
    ne_of_gt (Real.sqrt_pos.mpr h4pi)
  have hsqrtt : Real.sqrt τ ≠ 0 :=
    ne_of_gt (Real.sqrt_pos.mpr hτ)
  rw [show 4 * Real.pi * τ = (4 * Real.pi) * τ by ring,
    Real.sqrt_mul h4pi.le τ]
  rw [Real.rpow_neg hτ.le, Real.sqrt_eq_rpow]
  field_simp [hsqrt4pi, hsqrtt]
  rw [Real.sqrt_eq_rpow]

theorem wholeLineCauchyHeatGradOp_norm_le_rpow
    {f : ℝ → ℝ} {M τ : ℝ}
    (hτ : 0 < τ) (hM : 0 ≤ M) (hf : ∀ y, |f y| ≤ M) (x : ℝ) :
    ‖wholeLineCauchyHeatGradOp τ f x‖ ≤
      ((2 / Real.sqrt (4 * Real.pi)) * M) *
        τ ^ (-(1 / 2 : ℝ)) := by
  rw [Real.norm_eq_abs]
  have hbase := wholeLineCauchyHeatGradOp_abs_le hτ hM hf x
  have hexp_le : Real.exp (-τ) ≤ 1 :=
    Real.exp_le_one_iff.mpr (by linarith)
  have hinner_nonneg : 0 ≤ (2 / Real.sqrt (4 * Real.pi * τ)) * M := by
    positivity
  calc
    |wholeLineCauchyHeatGradOp τ f x|
        ≤ Real.exp (-τ) * ((2 / Real.sqrt (4 * Real.pi * τ)) * M) := hbase
    _ ≤ 1 * ((2 / Real.sqrt (4 * Real.pi * τ)) * M) :=
      mul_le_mul_of_nonneg_right hexp_le hinner_nonneg
    _ = ((2 / Real.sqrt (4 * Real.pi)) * M) *
          τ ^ (-(1 / 2 : ℝ)) := by
      rw [two_div_sqrt_four_pi_mul_eq_rpow_cauchy hτ]
      ring

theorem wholeLineCauchyGradientDuhamel_abs_le_sqrt_of_slice_bound
    {A t : ℝ} {F : ℝ → ℝ → ℝ} (ht : 0 < t) (x : ℝ)
    (hgrad_int : IntervalIntegrable
      (fun s : ℝ => wholeLineCauchyHeatGradOp (t - s) (F s) x)
      volume 0 t)
    (hslice : ∀ s, 0 ≤ s → s < t →
      |wholeLineCauchyHeatGradOp (t - s) (F s) x| ≤
        A * (t - s) ^ (-(1 / 2 : ℝ))) :
    |wholeLineCauchyGradientDuhamel F t x| ≤
      A * (2 * Real.sqrt t) := by
  have hdom_int : IntervalIntegrable
      (fun s : ℝ => A * (t - s) ^ (-(1 / 2 : ℝ))) volume 0 t :=
    (ShenWork.IntervalGradDuhamelBound.intervalIntegrable_sub_rpow_neg_half t).const_mul A
  have hne : ∀ᵐ s : ℝ ∂volume, s ≠ t := by
    rw [ae_iff]
    simp only [not_not, Set.setOf_eq_eq_singleton, Real.volume_singleton]
  have hae :
      (fun s : ℝ => |wholeLineCauchyHeatGradOp (t - s) (F s) x|)
        ≤ᵐ[volume.restrict (Set.Icc 0 t)]
      (fun s : ℝ => A * (t - s) ^ (-(1 / 2 : ℝ))) := by
    refine (ae_restrict_iff' measurableSet_Icc).2 ?_
    filter_upwards [hne] with s hs_ne hs_mem
    exact hslice s hs_mem.1 (lt_of_le_of_ne hs_mem.2 hs_ne)
  calc
    |wholeLineCauchyGradientDuhamel F t x|
        ≤ ∫ s in (0 : ℝ)..t,
            |wholeLineCauchyHeatGradOp (t - s) (F s) x| :=
      intervalIntegral.abs_integral_le_integral_abs ht.le
    _ ≤ ∫ s in (0 : ℝ)..t, A * (t - s) ^ (-(1 / 2 : ℝ)) :=
      intervalIntegral.integral_mono_ae_restrict ht.le
        hgrad_int.abs hdom_int hae
    _ = A * (2 * Real.sqrt t) := by
      rw [intervalIntegral.integral_const_mul,
        ShenWork.IntervalGradDuhamelBound.integral_sub_rpow_neg_half ht.le]

theorem wholeLineCauchyHeatOp_abs_bound_of_nonneg_time
    {t M : ℝ} {f : ℝ → ℝ}
    (hf_bound : ∀ x, |f x| ≤ M) (hM : 0 ≤ M)
    (hf_meas : AEStronglyMeasurable f volume) (ht : 0 ≤ t) :
    ∀ x, |wholeLineCauchyHeatOp t f x| ≤ M := by
  intro x
  by_cases ht0 : t = 0
  · subst t
    simpa [wholeLineCauchyHeatOp, modifiedSemigroup, heatSemigroup_zero] using hM
  · have htpos : 0 < t := lt_of_le_of_ne ht (Ne.symm ht0)
    have hbound :
        |wholeLineCauchyHeatOp t f x| ≤ Real.exp (-t) * M := by
      simpa [wholeLineCauchyHeatOp] using
        modifiedSemigroup_Linfty_bound hf_bound htpos hM hf_meas x
    have hexp_le : Real.exp (-t) ≤ 1 :=
      Real.exp_le_one_iff.mpr (by linarith)
    exact hbound.trans (by
      simpa using mul_le_mul_of_nonneg_right hexp_le hM)

theorem wholeLineCauchyValueDuhamel_abs_le_of_bound
    {C t : ℝ} {F : ℝ → ℝ → ℝ}
    (ht : 0 ≤ t) (hC : 0 ≤ C)
    (hF_bound : ∀ s ∈ Set.Icc (0 : ℝ) t, ∀ y, |F s y| ≤ C)
    (hF_meas : ∀ s ∈ Set.Icc (0 : ℝ) t,
      AEStronglyMeasurable (F s) volume) :
    ∀ x, |wholeLineCauchyValueDuhamel F t x| ≤ C * t := by
  intro x
  have hfinite : volume (Set.Icc (0 : ℝ) t) < ⊤ := measure_Icc_lt_top
  have hnorm :
      ‖∫ s in Set.Icc (0 : ℝ) t,
          wholeLineCauchyHeatOp (t - s) (F s) x‖ ≤
        C * volume.real (Set.Icc (0 : ℝ) t) := by
    refine norm_setIntegral_le_of_norm_le_const
      (μ := volume) (s := Set.Icc (0 : ℝ) t)
      (f := fun s => wholeLineCauchyHeatOp (t - s) (F s) x)
      hfinite ?_
    intro s hs
    simpa [Real.norm_eq_abs] using
      wholeLineCauchyHeatOp_abs_bound_of_nonneg_time
        (t := t - s) (M := C) (f := F s)
        (hF_bound s hs) hC (hF_meas s hs) (sub_nonneg.mpr hs.2) x
  have hvol : volume.real (Set.Icc (0 : ℝ) t) = t := by
    simpa using Real.volume_real_Icc_of_le ht
  simpa [wholeLineCauchyValueDuhamel, Real.norm_eq_abs, hvol] using hnorm

/-- Source paired with the shifted generator `Δ-I`. -/
def wholeLineCauchyShiftedReaction
    (p : CMParams) (u : ℝ → ℝ) (x : ℝ) : ℝ :=
  u x + wholeLineLogisticSource p u x

theorem wholeLineCauchyShiftedReaction_eq
    (p : CMParams) (u : ℝ → ℝ) (x : ℝ) :
    wholeLineCauchyShiftedReaction p u x =
      u x * (2 - (u x) ^ p.α) := by
  simp only [wholeLineCauchyShiftedReaction, wholeLineLogisticSource,
    reactionFun]
  ring

theorem wholeLineLogisticSource_continuous
    (p : CMParams) {u : ℝ → ℝ} (hu : Continuous u) :
    Continuous (wholeLineLogisticSource p u) := by
  unfold wholeLineLogisticSource reactionFun
  exact hu.mul
    (continuous_const.sub
      ((Real.continuous_rpow_const (by linarith [p.hα])).comp hu))

theorem wholeLineCauchyShiftedReaction_continuous
    (p : CMParams) {u : ℝ → ℝ} (hu : Continuous u) :
    Continuous (wholeLineCauchyShiftedReaction p u) :=
  hu.add (wholeLineLogisticSource_continuous p hu)

theorem wholeLineCauchyShiftedReaction_abs_le
    (p : CMParams) {M : ℝ} {u : ℝ → ℝ}
    (hM : 0 ≤ M) (huM : ∀ x, u x ∈ Set.Icc (0 : ℝ) M) (x : ℝ) :
    |wholeLineCauchyShiftedReaction p u x| ≤
      M + M * (1 + M ^ p.α) := by
  calc
    |wholeLineCauchyShiftedReaction p u x|
        ≤ |u x| + |wholeLineLogisticSource p u x| := abs_add_le _ _
    _ ≤ M + M * (1 + M ^ p.α) :=
      add_le_add (by simpa [abs_of_nonneg (huM x).1] using (huM x).2)
        (wholeLineLogisticSource_abs_le p hM huM x)

theorem wholeLineCauchyShiftedReaction_diff_abs_le
    (p : CMParams) {M D : ℝ} {u w : ℝ → ℝ}
    (hM : 0 ≤ M)
    (huM : ∀ x, u x ∈ Set.Icc (0 : ℝ) M)
    (hwM : ∀ x, w x ∈ Set.Icc (0 : ℝ) M)
    (hD : ∀ x, |u x - w x| ≤ D) (x : ℝ) :
    |wholeLineCauchyShiftedReaction p u x -
        wholeLineCauchyShiftedReaction p w x| ≤
      (1 + reactionLip p.α M) * D := by
  have hD0 : 0 ≤ D := (abs_nonneg (u 0 - w 0)).trans (hD 0)
  have hreact0 : 0 ≤ reactionLip p.α M :=
    reactionLip_nonneg p.hα hM
  have hsplit :
      wholeLineCauchyShiftedReaction p u x -
          wholeLineCauchyShiftedReaction p w x =
        (u x - w x) +
          (wholeLineLogisticSource p u x -
            wholeLineLogisticSource p w x) := by
    simp only [wholeLineCauchyShiftedReaction]
    ring
  rw [hsplit]
  calc
    |(u x - w x) +
        (wholeLineLogisticSource p u x -
          wholeLineLogisticSource p w x)|
        ≤ |u x - w x| +
            |wholeLineLogisticSource p u x -
              wholeLineLogisticSource p w x| := abs_add_le _ _
    _ ≤ D + reactionLip p.α M * D :=
      add_le_add (hD x)
        (wholeLineLogisticSource_diff_abs_le p hM huM hwM hD x)
    _ = (1 + reactionLip p.α M) * D := by ring

/-- The divergence-form flux Duhamel leg. -/
def wholeLineCauchyChemDuhamel
    (p : CMParams) (U : ℝ → ℝ → ℝ) (t x : ℝ) : ℝ :=
  -p.χ * wholeLineCauchyGradientDuhamel
    (fun s => wholeLineChemotaxisFlux p (U s)) t x

/-- The shifted logistic Duhamel leg. -/
def wholeLineCauchyReactionDuhamel
    (p : CMParams) (U : ℝ → ℝ → ℝ) (t x : ℝ) : ℝ :=
  wholeLineCauchyValueDuhamel
    (fun s => wholeLineCauchyShiftedReaction p (U s)) t x

/-- Correct whole-line mild map for the original parabolic equation.  The
zero-time branch records the datum because the raw Gaussian definition uses a
zero kernel at `t=0`; the positive-time formula has the correct initial trace. -/
def wholeLineCauchyMildMap
    (p : CMParams) (u₀ : ℝ → ℝ) (U : ℝ → ℝ → ℝ)
    (t x : ℝ) : ℝ :=
  if t = 0 then u₀ x
  else
    wholeLineCauchyHeatOp t u₀ x +
      wholeLineCauchyChemDuhamel p U t x +
      wholeLineCauchyReactionDuhamel p U t x

theorem wholeLineCauchyMildMap_zero
    (p : CMParams) (u₀ : ℝ → ℝ) (U : ℝ → ℝ → ℝ) (x : ℝ) :
    wholeLineCauchyMildMap p u₀ U 0 x = u₀ x := by
  simp [wholeLineCauchyMildMap]

/-- Spatial sup-Lipschitz constant of the coupled chemotaxis flux. -/
def wholeLineCauchyFluxLip (p : CMParams) (M : ℝ) : ℝ :=
  rpowLip p.m M * M ^ p.γ + M ^ p.m * rpowLip p.γ M

theorem wholeLineCauchyFluxLip_nonneg
    (p : CMParams) {M : ℝ} (hM : 0 ≤ M) :
    0 ≤ wholeLineCauchyFluxLip p M := by
  unfold wholeLineCauchyFluxLip
  exact add_nonneg
    (mul_nonneg (rpowLip_nonneg p.hm hM) (Real.rpow_nonneg hM _))
    (mul_nonneg (Real.rpow_nonneg hM _) (rpowLip_nonneg p.hγ hM))

/-- The coefficient obtained after integrating the Gaussian gradient
singularity over a time window. -/
def wholeLineCauchyChemGradientRate (p : CMParams) (M : ℝ) : ℝ :=
  4 * wholeLineCauchyFluxLip p M / Real.sqrt (4 * Real.pi)

theorem wholeLineCauchyChemGradientRate_nonneg
    (p : CMParams) {M : ℝ} (hM : 0 ≤ M) :
    0 ≤ wholeLineCauchyChemGradientRate p M := by
  unfold wholeLineCauchyChemGradientRate
  exact div_nonneg
    (mul_nonneg (by norm_num) (wholeLineCauchyFluxLip_nonneg p hM))
    (Real.sqrt_nonneg _)

/-- Translation in the spatial argument commutes with the heat-kernel
derivative for every time parameter, including the zero-kernel convention at
nonpositive times. -/
theorem deriv_heatKernel_translated_left_global
    (τ x y : ℝ) :
    deriv (fun z : ℝ => heatKernel τ (z - y)) x =
      deriv (fun z : ℝ => heatKernel τ z) (x - y) := by
  by_cases hτ : 0 < τ
  · calc
      deriv (fun z : ℝ => heatKernel τ (z - y)) x =
          -((x - y) / (2 * τ)) * heatKernel τ (x - y) :=
        deriv_heatKernel_translated_left hτ x y
      _ = deriv (fun z : ℝ => heatKernel τ z) (x - y) :=
        (deriv_heatKernel hτ (x - y)).symm
  · have hτnonpos : τ ≤ 0 := le_of_not_gt hτ
    have hleft : (fun z : ℝ => heatKernel τ (z - y)) = fun _ : ℝ => 0 := by
      funext z
      exact ShenWork.IntervalNeumannFullKernel.heatKernel_of_nonpos
        hτnonpos (z - y)
    have hright : (fun z : ℝ => heatKernel τ z) = fun _ : ℝ => 0 := by
      funext z
      exact ShenWork.IntervalNeumannFullKernel.heatKernel_of_nonpos hτnonpos z
    rw [hleft, hright, deriv_const, deriv_const]

/-- Joint measurability of the bounded-input Gaussian B-operator in the time
variable.  This is the whole-line counterpart of the interval full-kernel
`s_dependent` lemma. -/
theorem wholeLineHeatGradOp_s_dependent_aestronglyMeasurable
    {t : ℝ} {F : ℝ → ℝ → ℝ}
    (hF_ae : AEStronglyMeasurable (Function.uncurry F)
      ((volume.restrict (Set.uIoc (0 : ℝ) t)).prod volume))
    (x : ℝ) :
    AEStronglyMeasurable
      (fun s : ℝ => wholeLineCauchyHeatGradOp (t - s) (F s) x)
      (volume.restrict (Set.uIoc (0 : ℝ) t)) := by
  let J : ℝ × ℝ → ℝ := fun w =>
    Real.exp (-(t - w.1)) *
      (deriv (fun z : ℝ => heatKernel (t - w.1) (z - w.2)) x *
        F w.1 w.2)
  have hderiv_meas : Measurable (fun w : ℝ × ℝ =>
      deriv (fun z : ℝ => heatKernel (t - w.1) (z - w.2)) x) := by
    have heq : (fun w : ℝ × ℝ =>
        deriv (fun z : ℝ => heatKernel (t - w.1) (z - w.2)) x) =
        fun w : ℝ × ℝ =>
          deriv (fun z : ℝ => heatKernel (t - w.1) z) (x - w.2) := by
      funext w
      exact deriv_heatKernel_translated_left_global (t - w.1) x w.2
    rw [heq]
    exact ShenWork.IntervalNeumannFullKernel.measurable_deriv_heatKernel_comp
      (p := fun w => x - w.2) (by fun_prop) t
  have hJ_ae : AEStronglyMeasurable J
      ((volume.restrict (Set.uIoc (0 : ℝ) t)).prod volume) := by
    dsimp [J]
    simpa [Function.uncurry, mul_assoc] using
      (((by fun_prop : Continuous fun w : ℝ × ℝ =>
        Real.exp (-(t - w.1))).aestronglyMeasurable.mul
          hderiv_meas.aestronglyMeasurable).mul hF_ae)
  have hfubini :=
    MeasureTheory.AEStronglyMeasurable.integral_prod_right'
      (μ := volume.restrict (Set.uIoc (0 : ℝ) t))
      (ν := volume) (f := J) hJ_ae
  simpa [J, wholeLineCauchyHeatGradOp, mul_assoc] using hfubini

/-- A jointly measurable uniformly bounded source generates an integrable
gradient-Duhamel time slice.  The proof dominates by the already integrated
`(t-s)^(-1/2)` kernel. -/
theorem wholeLineHeatGradOp_intervalIntegrable_of_jointMeasurable
    {t C : ℝ} (ht : 0 < t) (hC : 0 ≤ C) {F : ℝ → ℝ → ℝ}
    (hF_ae : AEStronglyMeasurable (Function.uncurry F)
      ((volume.restrict (Set.uIoc (0 : ℝ) t)).prod volume))
    (hF_bound : ∀ s ∈ Set.Ioc (0 : ℝ) t, ∀ y, |F s y| ≤ C)
    (x : ℝ) :
    IntervalIntegrable
      (fun s : ℝ => wholeLineCauchyHeatGradOp (t - s) (F s) x)
      volume 0 t := by
  rw [intervalIntegrable_iff]
  have hmeas : AEStronglyMeasurable
      (fun s : ℝ => wholeLineCauchyHeatGradOp (t - s) (F s) x)
      (volume.restrict (Set.uIoc (0 : ℝ) t)) :=
    wholeLineHeatGradOp_s_dependent_aestronglyMeasurable hF_ae x
  have hdom_int : IntegrableOn
      (fun s : ℝ => ((2 / Real.sqrt (4 * Real.pi)) * C) *
        (t - s) ^ (-(1 / 2 : ℝ)))
      (Set.uIoc (0 : ℝ) t) volume := by
    rw [← intervalIntegrable_iff]
    exact
      (ShenWork.IntervalGradDuhamelBound.intervalIntegrable_sub_rpow_neg_half t).const_mul
        ((2 / Real.sqrt (4 * Real.pi)) * C)
  have hne : ∀ᵐ s : ℝ ∂volume, s ≠ t := by
    rw [ae_iff]
    simp only [not_not, Set.setOf_eq_eq_singleton]
    exact Real.volume_singleton
  have hae : ∀ᵐ s ∂(volume.restrict (Set.uIoc (0 : ℝ) t)),
      ‖wholeLineCauchyHeatGradOp (t - s) (F s) x‖ ≤
        ((2 / Real.sqrt (4 * Real.pi)) * C) *
          (t - s) ^ (-(1 / 2 : ℝ)) := by
    rw [Set.uIoc_of_le ht.le, ae_restrict_iff' measurableSet_Ioc]
    filter_upwards [hne] with s hs_ne hs
    exact wholeLineCauchyHeatGradOp_norm_le_rpow
      (τ := t - s) (M := C) (f := F s)
      (sub_pos.mpr (lt_of_le_of_ne hs.2 hs_ne)) hC
      (hF_bound s hs) x
  exact Integrable.mono' hdom_int.integrable hmeas hae

/-- The direct source-difference gradient Duhamel term. -/
def wholeLineCauchyChemDifferenceDuhamel
    (p : CMParams) (U W : ℝ → ℝ → ℝ) (t x : ℝ) : ℝ :=
  wholeLineCauchyGradientDuhamel
    (fun s y => wholeLineChemotaxisFlux p (U s) y -
      wholeLineChemotaxisFlux p (W s) y) t x

/-- Integration of the flux sup-Lipschitz estimate produces exactly the
short-time `sqrt(t)` contraction rate. -/
theorem wholeLineCauchyChemDifferenceDuhamel_abs_le
    (p : CMParams) {M D t : ℝ} {U W : ℝ → ℝ → ℝ}
    (hM : 0 ≤ M) (hD0 : 0 ≤ D) (ht : 0 < t)
    (hU : ∀ s ∈ Set.Icc (0 : ℝ) t, IsCUnifBdd (U s))
    (hW : ∀ s ∈ Set.Icc (0 : ℝ) t, IsCUnifBdd (W s))
    (hUM : ∀ s ∈ Set.Icc (0 : ℝ) t, ∀ y, U s y ∈ Set.Icc (0 : ℝ) M)
    (hWM : ∀ s ∈ Set.Icc (0 : ℝ) t, ∀ y, W s y ∈ Set.Icc (0 : ℝ) M)
    (hD : ∀ s ∈ Set.Icc (0 : ℝ) t, ∀ y, |U s y - W s y| ≤ D)
    (x : ℝ)
    (hInt : IntervalIntegrable
      (fun s : ℝ => wholeLineCauchyHeatGradOp (t - s)
        (fun y => wholeLineChemotaxisFlux p (U s) y -
          wholeLineChemotaxisFlux p (W s) y) x)
      volume 0 t) :
    |wholeLineCauchyChemDifferenceDuhamel p U W t x| ≤
      wholeLineCauchyChemGradientRate p M * Real.sqrt t * D := by
  let L := wholeLineCauchyFluxLip p M
  have hL0 : 0 ≤ L := wholeLineCauchyFluxLip_nonneg p hM
  have hLD0 : 0 ≤ L * D := mul_nonneg hL0 hD0
  have hbound : ∀ s, 0 ≤ s → s < t → ∀ y,
      |wholeLineChemotaxisFlux p (U s) y -
        wholeLineChemotaxisFlux p (W s) y| ≤ L * D := by
    intro s hs0 hst y
    have hs : s ∈ Set.Icc (0 : ℝ) t := ⟨hs0, hst.le⟩
    simpa [L, wholeLineCauchyFluxLip] using
      wholeLineChemotaxisFlux_diff_abs_le p hM (hU s hs) (hW s hs)
        (hUM s hs) (hWM s hs) (hD s hs) y
  have hgrad :=
    wholeLineCauchyGradientDuhamel_abs_le_sqrt_of_slice_bound
      (A := (2 / Real.sqrt (4 * Real.pi)) * (L * D))
      (t := t)
      (F := fun s y => wholeLineChemotaxisFlux p (U s) y -
        wholeLineChemotaxisFlux p (W s) y)
      ht x hInt (by
        intro s hs0 hst
        simpa [Real.norm_eq_abs] using
          wholeLineCauchyHeatGradOp_norm_le_rpow
            (τ := t - s) (M := L * D)
            (f := fun y => wholeLineChemotaxisFlux p (U s) y -
              wholeLineChemotaxisFlux p (W s) y)
            (sub_pos.mpr hst) hLD0 (hbound s hs0 hst) x)
  calc
    |wholeLineCauchyChemDifferenceDuhamel p U W t x|
        ≤ ((2 / Real.sqrt (4 * Real.pi)) * (L * D)) *
            (2 * Real.sqrt t) := by
          simpa [wholeLineCauchyChemDifferenceDuhamel] using hgrad
    _ = wholeLineCauchyChemGradientRate p M * Real.sqrt t * D := by
      simp only [wholeLineCauchyChemGradientRate, L]
      ring

/-- Joint measurability of the flux difference discharges the only time-
integrability side condition in the preceding estimate. -/
theorem wholeLineCauchyChemDifferenceDuhamel_abs_le_of_jointMeasurable
    (p : CMParams) {M D t : ℝ} {U W : ℝ → ℝ → ℝ}
    (hM : 0 ≤ M) (hD0 : 0 ≤ D) (ht : 0 < t)
    (hU : ∀ s ∈ Set.Icc (0 : ℝ) t, IsCUnifBdd (U s))
    (hW : ∀ s ∈ Set.Icc (0 : ℝ) t, IsCUnifBdd (W s))
    (hUM : ∀ s ∈ Set.Icc (0 : ℝ) t, ∀ y, U s y ∈ Set.Icc (0 : ℝ) M)
    (hWM : ∀ s ∈ Set.Icc (0 : ℝ) t, ∀ y, W s y ∈ Set.Icc (0 : ℝ) M)
    (hD : ∀ s ∈ Set.Icc (0 : ℝ) t, ∀ y, |U s y - W s y| ≤ D)
    (hF_ae : AEStronglyMeasurable
      (Function.uncurry (fun s y => wholeLineChemotaxisFlux p (U s) y -
        wholeLineChemotaxisFlux p (W s) y))
      ((volume.restrict (Set.uIoc (0 : ℝ) t)).prod volume))
    (x : ℝ) :
    |wholeLineCauchyChemDifferenceDuhamel p U W t x| ≤
      wholeLineCauchyChemGradientRate p M * Real.sqrt t * D := by
  let L := wholeLineCauchyFluxLip p M
  have hL0 : 0 ≤ L := wholeLineCauchyFluxLip_nonneg p hM
  have hLD0 : 0 ≤ L * D := mul_nonneg hL0 hD0
  have hsource_bound : ∀ s ∈ Set.Ioc (0 : ℝ) t, ∀ y,
      |wholeLineChemotaxisFlux p (U s) y -
        wholeLineChemotaxisFlux p (W s) y| ≤ L * D := by
    intro s hs y
    have hs' : s ∈ Set.Icc (0 : ℝ) t := ⟨hs.1.le, hs.2⟩
    simpa [L, wholeLineCauchyFluxLip] using
      wholeLineChemotaxisFlux_diff_abs_le p hM (hU s hs') (hW s hs')
        (hUM s hs') (hWM s hs') (hD s hs') y
  exact wholeLineCauchyChemDifferenceDuhamel_abs_le p hM hD0 ht
    hU hW hUM hWM hD x
    (wholeLineHeatGradOp_intervalIntegrable_of_jointMeasurable
      ht hLD0 hF_ae hsource_bound x)

/-- Direct shifted-reaction source difference. -/
def wholeLineCauchyReactionDifference
    (p : CMParams) (U W : ℝ → ℝ → ℝ) (s y : ℝ) : ℝ :=
  wholeLineCauchyShiftedReaction p (U s) y -
    wholeLineCauchyShiftedReaction p (W s) y

/-- The value Duhamel leg has the standard linear-in-time contraction rate. -/
theorem wholeLineCauchyReactionDifferenceDuhamel_abs_le
    (p : CMParams) {M D t : ℝ} {U W : ℝ → ℝ → ℝ}
    (hM : 0 ≤ M) (hD0 : 0 ≤ D) (ht : 0 ≤ t)
    (hU : ∀ s ∈ Set.Icc (0 : ℝ) t, IsCUnifBdd (U s))
    (hW : ∀ s ∈ Set.Icc (0 : ℝ) t, IsCUnifBdd (W s))
    (hUM : ∀ s ∈ Set.Icc (0 : ℝ) t, ∀ y, U s y ∈ Set.Icc (0 : ℝ) M)
    (hWM : ∀ s ∈ Set.Icc (0 : ℝ) t, ∀ y, W s y ∈ Set.Icc (0 : ℝ) M)
    (hD : ∀ s ∈ Set.Icc (0 : ℝ) t, ∀ y, |U s y - W s y| ≤ D)
    (x : ℝ) :
    |wholeLineCauchyValueDuhamel
        (wholeLineCauchyReactionDifference p U W) t x| ≤
      (1 + reactionLip p.α M) * t * D := by
  have hL0 : 0 ≤ 1 + reactionLip p.α M := by
    linarith [reactionLip_nonneg p.hα hM]
  have hLD0 : 0 ≤ (1 + reactionLip p.α M) * D :=
    mul_nonneg hL0 hD0
  have hraw := wholeLineCauchyValueDuhamel_abs_le_of_bound
    (C := (1 + reactionLip p.α M) * D) (t := t)
    (F := wholeLineCauchyReactionDifference p U W)
    ht hLD0 (by
      intro s hs y
      exact wholeLineCauchyShiftedReaction_diff_abs_le p hM
        (hUM s hs) (hWM s hs) (hD s hs) y)
    (by
      intro s hs
      exact ((wholeLineCauchyShiftedReaction_continuous p (hU s hs).1).sub
        (wholeLineCauchyShiftedReaction_continuous p (hW s hs).1)).aestronglyMeasurable)
    x
  calc
    |wholeLineCauchyValueDuhamel
        (wholeLineCauchyReactionDifference p U W) t x|
        ≤ ((1 + reactionLip p.α M) * D) * t := hraw
    _ = (1 + reactionLip p.α M) * t * D := by ring

section WholeLineCauchyDuhamelAxiomAudit

#print axioms wholeLineCauchyShiftedReaction_eq
#print axioms wholeLineCauchyShiftedReaction_abs_le
#print axioms wholeLineCauchyShiftedReaction_diff_abs_le
#print axioms wholeLineCauchyMildMap_zero
#print axioms wholeLineHeatGradOp_s_dependent_aestronglyMeasurable
#print axioms wholeLineHeatGradOp_intervalIntegrable_of_jointMeasurable
#print axioms wholeLineCauchyChemDifferenceDuhamel_abs_le
#print axioms wholeLineCauchyChemDifferenceDuhamel_abs_le_of_jointMeasurable
#print axioms wholeLineCauchyReactionDifferenceDuhamel_abs_le

end WholeLineCauchyDuhamelAxiomAudit

end ShenWork.Paper1
