import ShenWork.Paper2.IntervalDomainThm11ChiNegativeResidual

#check ShenWork.Paper2.ChiNegativeResidual.ChiNegativeNonminimalCoupledExistenceResidual
#check ShenWork.Paper2.ChiNegativeResidual.ChiNegativeNonminimalCoupledExistenceResidual.localExistence
#check ShenWork.Paper2.ChiNegativeResidual.ChiNegativeNonminimalCoupledExistenceResidual.globalSolutionExists
#check ShenWork.Paper2.ChiNegativeResidual.nonminimal_supNorm_bound_from_Lemma_3_1_intervalDomain_and_trace
#check ShenWork.Paper2.ChiNegativeResidual.Theorem_1_1_intervalDomain_chiNegative_nonminimal_of_coupledResidual

#print axioms ShenWork.Paper2.ChiNegativeResidual.nonminimal_supNorm_bound_from_Lemma_3_1_intervalDomain_and_trace
#print axioms ShenWork.Paper2.ChiNegativeResidual.Theorem_1_1_intervalDomain_chiNegative_nonminimal_of_coupledResidual

