import ShenWork.Paper2.IntervalRestartVariationOfConstants
import ShenWork.PDE.IntervalResolverJointC2C2Coeff
import ShenWork.PDE.IntervalPhysicalResolverDataConcrete
import ShenWork.PDE.IntervalCoupledRegularityBootstrap
import ShenWork.Paper2.IntervalConjugatePicard

open Filter Topology Set
open ShenWork.IntervalDomain (intervalDomainPoint)
open ShenWork.IntervalSourceCoefficientTimeC1 (localRestartCoeff)
open ShenWork.IntervalResolverSpectralTimeC2 (DuhamelSourceTimeC2Coeff)
open ShenWork.IntervalResolverJointC2 (ResolverHasSpectralAgreementC2Coeff)
open ShenWork.IntervalResolverTimeRegularity (ResolverHasSpectralAgreement)
open ShenWork.IntervalResolverJointC2PhysicalConcrete (resolverTimeCoeff)
open ShenWork.IntervalCoupledRegularityBootstrap (coupledChemicalConcentration)
open ShenWork.IntervalConjugatePicard (conjugatePicardIter)
open ShenWork.CosineSpectrum (cosineMode)

noncomputable section

namespace ShenWork.Paper2.ResolverLevel0SpectralC2Coeff

/-- Level-0 trajectory used in the B-form Picard construction: the heat semigroup
iterate `conjugatePicardIter p u₀ 0`. -/
abbrev heatLevel0 (p : CM2Params) (u₀ : intervalDomainPoint → ℝ) :
    ℝ → intervalDomainPoint → ℝ :=
  conjugatePicardIter p u₀ 0

/-- Restart offset for a positive interior time `t₀`: the positive half-time
`t₀ / 2`. -/
def halfOffset (t₀ : ℝ) : ℝ :=
  t₀ / 2

/-- Initial coefficients at the restart offset. -/
def level0ResolverRestartA0
    (p : CM2Params) (u₀ : intervalDomainPoint → ℝ) (t₀ : ℝ) : ℕ → ℝ :=
  fun k => resolverTimeCoeff p (heatLevel0 p u₀) k (halfOffset t₀)

/-- Restart source coefficients generated by the scalar ODE
`c' = a - λ c` for `c(t) = resolverTimeCoeff p (heatLevel0 p u₀) k t`.

The `k`-th source is
`deriv c_k(offset + ρ) + λ_k c_k(offset + ρ)`. -/
def level0ResolverRestartSource
    (p : CM2Params) (u₀ : intervalDomainPoint → ℝ) (t₀ : ℝ) : ℝ → ℕ → ℝ :=
  fun ρ k =>
    deriv (resolverTimeCoeff p (heatLevel0 p u₀) k) (halfOffset t₀ + ρ) +
      unitIntervalCosineEigenvalue k *
        resolverTimeCoeff p (heatLevel0 p u₀) k (halfOffset t₀ + ρ)

/-- The coefficient-level variation-of-constants identity specialized to the
level-0 resolver coefficient family.

This is the concrete step requested in the prompt: after restarting at
`offset = t₀/2`, the local restart coefficient recovers
`resolverTimeCoeff ... k s` for `s` near `t₀`, provided `s ≥ offset`.
The only analytic inputs are the C¹ facts needed to invoke
`localRestartCoeff_variation_of_constants` for the scalar function
`t ↦ resolverTimeCoeff p (heatLevel0 p u₀) k t`. -/
theorem level0Resolver_localRestartCoeff_eq
    (p : CM2Params) (u₀ : intervalDomainPoint → ℝ) (t₀ s : ℝ)
    (hs : halfOffset t₀ ≤ s)
    (k : ℕ)
    (hderiv : ∀ t : ℝ,
      HasDerivAt (resolverTimeCoeff p (heatLevel0 p u₀) k)
        (deriv (resolverTimeCoeff p (heatLevel0 p u₀) k) t) t)
    (hderiv_cont : Continuous
      (fun t : ℝ => deriv (resolverTimeCoeff p (heatLevel0 p u₀) k) t)) :
    localRestartCoeff
        (level0ResolverRestartA0 p u₀ t₀)
        (level0ResolverRestartSource p u₀ t₀)
        (s - halfOffset t₀) k =
      resolverTimeCoeff p (heatLevel0 p u₀) k s := by
  have hρ : 0 ≤ s - halfOffset t₀ := sub_nonneg.mpr hs
  have hvoc :=
    ShenWork.Paper2.RestartVariationOfConstants.localRestartCoeff_variation_of_constants
      (c := resolverTimeCoeff p (heatLevel0 p u₀) k)
      hderiv hderiv_cont
      (halfOffset t₀) (s - halfOffset t₀) hρ k
  have hηρ : halfOffset t₀ + (s - halfOffset t₀) = s := by ring
  simpa [level0ResolverRestartA0, level0ResolverRestartSource, hηρ]
    using hvoc

/-- Assemble the strengthened spectral-agreement package for the heat Level0
resolver from the variation-of-constants identity.

The proof deliberately keeps four analytic inputs as `sorry` blocks:

* `ha0_bound`: uniform bound for the restart initial coefficients at `t₀/2`;
* `srcC2`: the strengthened `DuhamelSourceTimeC2Coeff` package for the restart
  source. This is the largest missing bridge, because the existing physical
  resolver route bypasses the spectral λ²/λ³ ladder;
* `hcoeff_deriv` / `hcoeff_deriv_cont`: scalar C¹ facts for each
  `resolverTimeCoeff`; these should follow from the positive-time source C² data
  and the constant elliptic weight factorization;
* `hresolver_series`: cosine reconstruction of the concrete resolver value.

Everything else is bookkeeping plus the variation-of-constants identity. -/
theorem resolverHasSpectralAgreementC2Coeff_heatLevel0
    (p : CM2Params) (u₀ : intervalDomainPoint → ℝ) {T : ℝ} (_hT : 0 < T) :
    ResolverHasSpectralAgreementC2Coeff T
      (coupledChemicalConcentration p (heatLevel0 p u₀)) := by
  let u : ℝ → intervalDomainPoint → ℝ := heatLevel0 p u₀

  /- Cosine reconstruction of the concrete elliptic resolver.
     This should be obtained from `intervalNeumannResolverR` /
     `resolverR_eq_cosineSeries` and the definition of `resolverTimeCoeff`. -/
  have hresolver_series : ∀ s : ℝ, 0 < s → s < T → ∀ x : intervalDomainPoint,
      coupledChemicalConcentration p u s x =
        ∑' k : ℕ, resolverTimeCoeff p u k s * cosineMode k x.1 := by
    intro s _hs _hsT x
    have hlift := ShenWork.IntervalResolverJointC2PhysicalConcrete.coupledChemical_lift_eq_series
      (p := p) (u := u) (t := s) (x := x.1) x.2
    have hlift_eq : ShenWork.IntervalDomain.intervalDomainLift
        (coupledChemicalConcentration p u s) x.1 = coupledChemicalConcentration p u s x := by
      simp [ShenWork.IntervalDomain.intervalDomainLift, x.2]
    rw [hlift_eq] at hlift
    simpa [ShenWork.IntervalResolverJointC2Physical.boundedWeightJointTerm] using hlift

  have hmake : ∀ t₀ : ℝ, 0 < t₀ → t₀ < T →
      ∃ (a₀ : ℕ → ℝ) (M : ℝ) (_ : 0 ≤ M) (_ : ∀ n, |a₀ n| ≤ M)
        (a : ℝ → ℕ → ℝ) (_ : DuhamelSourceTimeC2Coeff a) (offset : ℝ),
        (0 < t₀ - offset) ∧
        (∀ᶠ s in 𝓝 t₀, ∀ x : intervalDomainPoint,
          coupledChemicalConcentration p u s x =
            ∑' n, localRestartCoeff a₀ a (s - offset) n * cosineMode n x.1) := by
    intro t₀ ht₀ ht₀T
    let offset : ℝ := halfOffset t₀
    let a₀ : ℕ → ℝ := level0ResolverRestartA0 p u₀ t₀
    let a : ℝ → ℕ → ℝ := level0ResolverRestartSource p u₀ t₀

    have hoff_pos : 0 < offset := by
      dsimp [offset, halfOffset]
      linarith

    have hτ₀ : 0 < t₀ - offset := by
      dsimp [offset, halfOffset]
      linarith

    obtain ⟨M, hM, ha₀⟩ :
        ∃ M : ℝ, 0 ≤ M ∧ ∀ n : ℕ, |a₀ n| ≤ M := by
      -- TODO: bound the resolver coefficients at the fixed positive time
      -- `offset = t₀/2`.  For Level0 heat this should follow from the resolver
      -- cosine coefficient square/decay estimate plus `offset > 0` heat smoothing.
      -- A crude bound such as a finite sup/envelope at the positive time suffices.
      sorry

    have srcC2 : DuhamelSourceTimeC2Coeff a := by
      -- TODO: build the strengthened source package for
      --   a ρ k = c'_k(offset+ρ) + λ_k c_k(offset+ρ),
      -- where c_k(t) = resolverTimeCoeff p u k t.
      -- Required fields:
      --   * DuhamelSourceTimeC1 a: HasDerivAt in ρ, continuous adot,
      --     ℓ¹ envelope for a, uniform bound for adot;
      --   * λ-weighted and λ²-weighted envelopes for a;
      --   * λ-weighted and λ²-weighted envelopes for adot.
      -- For Level0 heat, these should come from positive-time exponential
      -- heat smoothing, resolver weight `1/(μ+λ_k)`, and the source-side
      -- `srcTimeCoeff_contDiffAt`/bounds.  This is not presently packaged in
      -- the repo; the committed physical resolver lane bypasses this structure.
      sorry

    have hcoeff_deriv : ∀ k : ℕ, ∀ t : ℝ,
        HasDerivAt (resolverTimeCoeff p u k)
          (deriv (resolverTimeCoeff p u k) t) t := by
      -- TODO: derive from positive-time `ContDiff` of resolver coefficients.
      -- If the heat Level0 coefficient family is only smooth on `(0,∞)`, then
      -- either use its smooth positive-time extension or replace the VOC lemma
      -- by a local/windowed variant.  The current VOC lemma has a global C¹
      -- hypothesis, so this block supplies exactly that interface.
      sorry

    have hcoeff_deriv_cont : ∀ k : ℕ,
        Continuous (fun t : ℝ => deriv (resolverTimeCoeff p u k) t) := by
      -- TODO: same source as above; `ContDiff ℝ 2` gives continuity of the first
      -- derivative.  Source-side theorem already present:
      -- `IntervalPhysicalSourceTimeC2Concrete.srcTimeCoeff_contDiffAt`, plus
      -- `resolverTimeCoeff_eq_weight_smul` transfers through the constant
      -- elliptic weight.
      sorry

    have hagree : ∀ᶠ s in 𝓝 t₀, ∀ x : intervalDomainPoint,
        coupledChemicalConcentration p u s x =
          ∑' n, localRestartCoeff a₀ a (s - offset) n * cosineMode n x.1 := by
      have hnear_time : Set.Ioo (0 : ℝ) T ∩ Set.Ioi offset ∈ 𝓝 t₀ := by
        exact Filter.inter_mem
          (isOpen_Ioo.mem_nhds ⟨ht₀, ht₀T⟩)
          (isOpen_Ioi.mem_nhds (by
            show halfOffset t₀ < t₀
            simp only [halfOffset]
            linarith))
      filter_upwards [hnear_time] with s hs x
      have hs0 : 0 < s := hs.1.1
      have hsT : s < T := hs.1.2
      have hsoff : offset ≤ s := le_of_lt hs.2
      have hcoeff_eq : ∀ k : ℕ,
          localRestartCoeff a₀ a (s - offset) k = resolverTimeCoeff p u k s := by
        intro k
        have h := level0Resolver_localRestartCoeff_eq
          (p := p) (u₀ := u₀) (t₀ := t₀) (s := s) hsoff k
          (hcoeff_deriv k) (hcoeff_deriv_cont k)
        simpa [u, a₀, a, offset] using h
      have hsum :
          (∑' k : ℕ, localRestartCoeff a₀ a (s - offset) k * cosineMode k x.1) =
            ∑' k : ℕ, resolverTimeCoeff p u k s * cosineMode k x.1 := by
        apply tsum_congr
        intro k
        rw [hcoeff_eq k]
      rw [hresolver_series s hs0 hsT x, ← hsum]

    exact ⟨a₀, M, hM, ha₀, a, srcC2, offset, hτ₀, hagree⟩

  refine ⟨?toSpectralAgreement, hmake⟩
  refine { exists_data := ?_ }
  intro t₀ ht₀ ht₀T
  rcases hmake t₀ ht₀ ht₀T with
    ⟨a₀, M, hM, ha₀, a, srcC2, offset, hτ₀, hagree⟩
  exact ⟨a₀, M, hM, ha₀, a, srcC2.toTimeC1, offset, hτ₀, hagree⟩

end ShenWork.Paper2.ResolverLevel0SpectralC2Coeff
