import ShenWork.Paper2.IntervalBFormCron2Concrete
import ShenWork.Paper2.IntervalDomainL2UniquenessCertificate

open Filter Topology Set MeasureTheory
open scoped Topology

open ShenWork.IntervalDomain
  (intervalDomain intervalDomainLift intervalDomainPoint intervalMeasure)
open ShenWork.IntervalConjugatePicard
  (ConjugateMildExistenceData conjugatePicardLimit)

noncomputable section

namespace ShenWork.Paper2.BFormPositiveDatumNegPart

/-!
Negative-part energy core for the cron2 B-form route.

This file is additive.  It proves the real-analysis pieces that do not depend
on the still-missing Sobolev/Duhamel plumbing:

* the a.e. disjoint-support chemotaxis cancellation;
* the weak-tested energy inequality once the standard time/spatial chain-rule
  identities and the reaction bound are supplied;
* the positive-time Gronwall argument which forces the negative-part energy to
  vanish.

The remaining PDE/Sobolev obligations are explicit fields of
`NegativePartEnergyCoreData`: the weak formulation itself, the chain-rule
identities for the test `-u_-`, positive-time energy differentiability, the
initial trace of the negative part, and the representative upgrade from
zero L² negative part to pointwise nonnegativity.
-/

/-- Lifted negative part of a spatial slice. -/
def negativePartLift (u : intervalDomainPoint → ℝ) : ℝ → ℝ :=
  fun x => negativePart (intervalDomainLift u x)

/-- Squared L² negative-part energy over `[0,1]`. -/
def negativePartEnergy (u : ℝ → intervalDomainPoint → ℝ) (t : ℝ) : ℝ :=
  ∫ x, (negativePartLift (u t) x) ^ 2 ∂ intervalMeasure 1

/-- Spatial dissipation generated by testing with `-u_-`. -/
def negativePartDissipation (u : ℝ → intervalDomainPoint → ℝ) (t : ℝ) : ℝ :=
  ∫ x, (deriv (negativePartLift (u t)) x) ^ 2 ∂ intervalMeasure 1

/-- The exact negative-part test function `φ = -u_-`. -/
def negativePartTest (u : ℝ → intervalDomainPoint → ℝ) (t : ℝ) : ℝ → ℝ :=
  fun x => -negativePartLift (u t) x

lemma negativePart_eq_neg_of_nonpos {r : ℝ} (hr : r ≤ 0) :
    negativePart r = -r := by
  simp [negativePart, hr]

/-- At a point where the slice is strictly positive, the negative part is
locally constant zero, hence its classical derivative vanishes. -/
lemma deriv_negativePartLift_eq_zero_of_pos
    {u : ℝ → ℝ} {x : ℝ} (hu : ContinuousAt u x) (hpos : 0 < u x) :
    deriv (fun y : ℝ => negativePart (u y)) x = 0 := by
  have hmem : u x ∈ Set.Ioi (0 : ℝ) := hpos
  have hnhds : Set.Ioi (0 : ℝ) ∈ 𝓝 (u x) :=
    isOpen_Ioi.mem_nhds hmem
  have hev_pos : ∀ᶠ y in 𝓝 x, u y ∈ Set.Ioi (0 : ℝ) :=
    hu hnhds
  have hev :
      (fun y : ℝ => negativePart (u y)) =ᶠ[𝓝 x] (fun _ : ℝ => 0) :=
    hev_pos.mono (fun y hy => negativePart_eq_zero_of_nonneg hy.le)
  rw [hev.deriv_eq]
  simp

/-- Pointwise classical form of the disjoint-support cancellation. -/
lemma truncatedChemotacticPower_mul_deriv_negativePartLift_eq_zero_of_continuousAt
    (p : CM2Params) {u : ℝ → ℝ} {x : ℝ}
    (hu : ContinuousAt u x) :
    truncatedChemotacticPower p (u x)
        * deriv (fun y : ℝ => negativePart (u y)) x = 0 := by
  by_cases hpos : 0 < u x
  · have hderiv := deriv_negativePartLift_eq_zero_of_pos hu hpos
    simp [hderiv]
  · have hflux :
        truncatedChemotacticPower p (u x) = 0 :=
      truncatedChemotacticPower_eq_zero_of_nonpos p (le_of_not_gt hpos)
    simp [hflux]

/-- A.e. Sobolev support form used by the weak estimate.

The only support input needed is that the weak derivative of `u_-` vanishes
a.e. on `{0 < u}`.  On the complementary set `{u ≤ 0}` the truncated flux
itself is zero. -/
lemma truncatedChemotacticPower_mul_negDeriv_eq_zero_ae
    (p : CM2Params) {μ : Measure ℝ} {u duNeg : ℝ → ℝ}
    (hdu_zero_on_pos : ∀ᵐ x ∂ μ, 0 < u x → duNeg x = 0) :
    (fun x => truncatedChemotacticPower p (u x) * duNeg x)
      =ᵐ[μ] fun _ => 0 := by
  filter_upwards [hdu_zero_on_pos] with x hx
  by_cases hpos : 0 < u x
  · simp [hx hpos]
  · have hflux :
        truncatedChemotacticPower p (u x) = 0 :=
      truncatedChemotacticPower_eq_zero_of_nonpos p (le_of_not_gt hpos)
    simp [hflux]

/-- Integral form of the a.e. disjoint-support cancellation. -/
theorem truncatedChemotacticPower_mul_negDeriv_integral_eq_zero
    (p : CM2Params) {u duNeg : ℝ → ℝ}
    (hdu_zero_on_pos :
      ∀ᵐ x ∂ intervalMeasure 1, 0 < u x → duNeg x = 0) :
    (∫ x, truncatedChemotacticPower p (u x) * duNeg x
        ∂ intervalMeasure 1) = 0 := by
  rw [MeasureTheory.integral_congr_ae
    (truncatedChemotacticPower_mul_negDeriv_eq_zero_ae
      (p := p) (μ := intervalMeasure 1) hdu_zero_on_pos)]
  simp

/-- A.e. disjoint-support cancellation for the faithful truncated flux.

Only the leading `positivePart u` factor matters.  On `{u ≤ 0}` it is zero;
on `{0 < u}` the weak derivative of `u_-` is zero by hypothesis. -/
lemma truncatedChemFluxLifted_mul_negDeriv_eq_zero_ae
    (p : CM2Params) {w : intervalDomainPoint → ℝ} {duNeg : ℝ → ℝ}
    (hdu_zero_on_pos :
      ∀ᵐ x ∂ intervalMeasure 1,
        0 < intervalDomainLift w x → duNeg x = 0) :
    (fun x => truncatedChemFluxLifted p w x * duNeg x)
      =ᵐ[intervalMeasure 1] fun _ => 0 := by
  filter_upwards [hdu_zero_on_pos] with x hx
  by_cases hpos : 0 < intervalDomainLift w x
  · simp [hx hpos]
  · have hpp :
        positivePart (intervalDomainLift w x) = 0 :=
      positivePart_eq_zero_of_nonpos (le_of_not_gt hpos)
    simp [truncatedChemFluxLifted, hpp]

/-- Integral cancellation for the faithful truncated flux. -/
theorem truncatedChemFluxLifted_mul_negDeriv_integral_eq_zero
    (p : CM2Params) {w : intervalDomainPoint → ℝ} {duNeg : ℝ → ℝ}
    (hdu_zero_on_pos :
      ∀ᵐ x ∂ intervalMeasure 1,
        0 < intervalDomainLift w x → duNeg x = 0) :
    (∫ x, truncatedChemFluxLifted p w x * duNeg x
        ∂ intervalMeasure 1) = 0 := by
  rw [MeasureTheory.integral_congr_ae
    (truncatedChemFluxLifted_mul_negDeriv_eq_zero_ae
      (p := p) (w := w) hdu_zero_on_pos)]
  simp

/-- Classical continuous-slice version of the cancellation, stated as an a.e.
identity for the actual classical derivative of `u_-`. -/
lemma truncatedChemotacticPower_mul_deriv_negativePart_eq_zero_ae_of_continuous
    (p : CM2Params) {u : ℝ → ℝ}
    (hu : ∀ x, ContinuousAt u x) :
    (fun x =>
        truncatedChemotacticPower p (u x)
          * deriv (fun y : ℝ => negativePart (u y)) x)
      =ᵐ[intervalMeasure 1] fun _ => 0 := by
  exact Eventually.of_forall fun x =>
    truncatedChemotacticPower_mul_deriv_negativePartLift_eq_zero_of_continuousAt
      p (hu x)

/-- Classical integral cancellation over `[0,1]`. -/
theorem truncatedChemotacticPower_mul_deriv_negativePart_integral_eq_zero
    (p : CM2Params) {u : ℝ → ℝ}
    (hu : ∀ x, ContinuousAt u x) :
    (∫ x,
        truncatedChemotacticPower p (u x)
          * deriv (fun y : ℝ => negativePart (u y)) x
        ∂ intervalMeasure 1) = 0 := by
  rw [MeasureTheory.integral_congr_ae
    (truncatedChemotacticPower_mul_deriv_negativePart_eq_zero_ae_of_continuous
      p hu)]
  simp

/-- Scalar one-sided reaction estimate for the truncated logistic source. -/
lemma truncatedLogisticLocal_mul_neg_negativePart_le
    (p : CM2Params) (r : ℝ) :
    truncatedLogisticLocal p r * (-negativePart r)
      ≤ p.a * (negativePart r) ^ 2 := by
  by_cases hpos : 0 < r
  · have hneg : negativePart r = 0 :=
      negativePart_eq_zero_of_nonneg hpos.le
    simp [hneg]
  · have hr : r ≤ 0 := le_of_not_gt hpos
    have hpospart : positivePart r = 0 :=
      positivePart_eq_zero_of_nonpos hr
    have hneg : negativePart r = -r :=
      negativePart_eq_neg_of_nonpos hr
    have hα_ne : p.α ≠ 0 := ne_of_gt p.hα
    simp [truncatedLogisticLocal, hpospart, hneg, Real.zero_rpow hα_ne]
    have hEq : r * p.a * r = p.a * r ^ 2 := by ring
    rw [hEq]

/-- Pointwise nonnegativity of the negative-part energy density. -/
lemma negativePartEnergyDensity_nonneg
    (u : ℝ → intervalDomainPoint → ℝ) (t x : ℝ) :
    0 ≤ (negativePartLift (u t) x) ^ 2 := by
  exact sq_nonneg _

/-- If the negative-part energy vanishes, then the lifted slice is nonnegative
a.e.  This is the L² conclusion before upgrading to a continuous representative. -/
theorem ae_nonneg_of_negativePartEnergy_eq_zero
    {u : ℝ → intervalDomainPoint → ℝ} {t : ℝ}
    (hint :
      Integrable (fun x => (negativePartLift (u t) x) ^ 2)
        (intervalMeasure 1))
    (hzero : negativePartEnergy u t = 0) :
    ∀ᵐ x ∂ intervalMeasure 1, 0 ≤ intervalDomainLift (u t) x := by
  have hnn :
      0 ≤ᵐ[intervalMeasure 1]
        fun x => (negativePartLift (u t) x) ^ 2 :=
    Eventually.of_forall fun x => negativePartEnergyDensity_nonneg u t x
  have hsq_zero :
      (fun x => (negativePartLift (u t) x) ^ 2)
        =ᵐ[intervalMeasure 1] fun _ => 0 :=
    (MeasureTheory.integral_eq_zero_iff_of_nonneg_ae hnn hint).1 hzero
  filter_upwards [hsq_zero] with x hx
  have hneg_zero : negativePart (intervalDomainLift (u t) x) = 0 := by
    have hx' : (negativePartLift (u t) x) ^ 2 = 0 := by simpa using hx
    exact sq_eq_zero_iff.mp hx'
  exact negativePart_eq_zero_iff.mp hneg_zero

/-- Positive-time scalar Gronwall-to-zero package.

This avoids any derivative requirement at `t = 0`: the Gronwall estimate is
only used from positive `s` to `t`, and the initial trace is the limit
`E(s) → 0` as `s → 0+`. -/
theorem energy_eq_zero_of_positive_time_gronwall
    {T : ℝ} {E : ℝ → ℝ}
    (hE_nonneg : ∀ t, 0 < t → t ≤ T → 0 ≤ E t)
    (hgronwall :
      ∃ K : ℝ, 0 ≤ K ∧
        ∀ s t, 0 < s → s ≤ t → t ≤ T →
          E t ≤ E s * Real.exp (K * (t - s)))
    (hinit :
      ∀ ε > 0, ∃ δ > 0, ∀ s, 0 < s → s < δ → s < T →
        E s < ε) :
    ∀ t, 0 < t → t ≤ T → E t = 0 := by
  intro t ht0 htT
  have hEt_nonneg : 0 ≤ E t := hE_nonneg t ht0 htT
  by_contra hEt_ne
  have hEt_pos : 0 < E t := lt_of_le_of_ne hEt_nonneg (Ne.symm hEt_ne)
  rcases hgronwall with ⟨K, hK_nonneg, hG⟩
  have hExp_pos : 0 < Real.exp (K * t) := Real.exp_pos _
  let ε : ℝ := E t / (2 * Real.exp (K * t))
  have hε_pos : 0 < ε :=
    div_pos hEt_pos (mul_pos (by norm_num) hExp_pos)
  rcases hinit ε hε_pos with ⟨δ, hδ_pos, hδ⟩
  let s : ℝ := min (δ / 2) (t / 2)
  have hs_pos : 0 < s := lt_min (by linarith) (by linarith)
  have hs_lt_δ : s < δ :=
    lt_of_le_of_lt (min_le_left _ _) (by linarith)
  have hs_lt_t : s < t :=
    lt_of_le_of_lt (min_le_right _ _) (by linarith)
  have hs_le_t : s ≤ t := le_of_lt hs_lt_t
  have hsT : s < T := lt_of_lt_of_le hs_lt_t htT
  have hEs_nonneg : 0 ≤ E s := hE_nonneg s hs_pos hsT.le
  have hEs_lt : E s < ε := hδ s hs_pos hs_lt_δ hsT
  have hExp_le : Real.exp (K * (t - s)) ≤ Real.exp (K * t) := by
    apply Real.exp_le_exp.mpr
    have hs_nonneg : 0 ≤ s := le_of_lt hs_pos
    nlinarith [mul_nonneg hK_nonneg hs_nonneg]
  have hEt_le := hG s t hs_pos hs_le_t htT
  have hEt_lt :
      E t < ε * Real.exp (K * t) := by
    calc
      E t ≤ E s * Real.exp (K * (t - s)) := hEt_le
      _ ≤ E s * Real.exp (K * t) :=
        mul_le_mul_of_nonneg_left hExp_le hEs_nonneg
      _ < ε * Real.exp (K * t) :=
        mul_lt_mul_of_pos_right hEs_lt hExp_pos
  have hhalf :
      ε * Real.exp (K * t) = E t / 2 := by
    dsimp [ε]
    field_simp [Real.exp_ne_zero (K * t)]
  have : E t < E t / 2 := by simpa [hhalf] using hEt_lt
  nlinarith

/-- The exact weak identity after inserting the test `φ = -u_-`. -/
def NegativePartWeakTestIdentityAt
    (p : CM2Params) (u : ℝ → intervalDomainPoint → ℝ) (t : ℝ) : Prop :=
  (∫ x,
      intervalDomainLift
          (fun z : intervalDomainPoint =>
            intervalDomain.timeDeriv u t z) x * negativePartTest u t x
      ∂ intervalMeasure 1)
    + (∫ x,
        deriv (intervalDomainLift (u t)) x * deriv (negativePartTest u t) x
        ∂ intervalMeasure 1)
    =
    p.χ₀ *
      (∫ x,
        truncatedChemFluxLifted p (u t) x
          * deriv (negativePartTest u t) x
        ∂ intervalMeasure 1)
    + (∫ x, truncatedLogisticLifted p (u t) x * negativePartTest u t x
        ∂ intervalMeasure 1)

/-- The all-test weak PDE gives the negative-part tested identity. -/
theorem negativePartWeakTestIdentityAt_of_weak
    {p : CM2Params} {T : ℝ} {u : ℝ → intervalDomainPoint → ℝ}
    (hweak : TruncatedWeakLocalPDE p T u)
    {t : ℝ} (ht : 0 < t) (htT : t ≤ T) :
    NegativePartWeakTestIdentityAt p u t := by
  simpa [NegativePartWeakTestIdentityAt, negativePartTest] using
    hweak t ht htT (negativePartTest u t)

/-- Standard chain-rule and bound data needed after the weak test `-u_-`.

The fields are exactly the Sobolev plumbing not present as full theorems in the
current tree.  The cancellation field is intentionally only the a.e. support
statement for `(u_-)_x`, because the integral cancellation is proved above. -/
structure NegativePartEnergyEstimateData
    (p : CM2Params) (T : ℝ) (u : ℝ → intervalDomainPoint → ℝ)
    (ell : ℝ) (E' : ℝ → ℝ) : Prop where
  weak : TruncatedWeakLocalPDE p T u
  neg_deriv_zero_on_pos :
    ∀ t, 0 < t → t ≤ T →
      ∀ᵐ x ∂ intervalMeasure 1,
        0 < intervalDomainLift (u t) x →
          deriv (negativePartLift (u t)) x = 0
  time_chain :
    ∀ t, 0 < t → t ≤ T →
      (∫ x,
          intervalDomainLift
              (fun z : intervalDomainPoint =>
                intervalDomain.timeDeriv u t z) x * negativePartTest u t x
          ∂ intervalMeasure 1)
        = (1 / 2 : ℝ) * E' t
  diffusion_chain :
    ∀ t, 0 < t → t ≤ T →
      (∫ x,
          deriv (intervalDomainLift (u t)) x * deriv (negativePartTest u t) x
          ∂ intervalMeasure 1)
        = negativePartDissipation u t
  diffusion_nonneg :
    ∀ t, 0 < t → t ≤ T → 0 ≤ negativePartDissipation u t
  reaction_bound :
    ∀ t, 0 < t → t ≤ T →
      (∫ x, truncatedLogisticLifted p (u t) x * negativePartTest u t x
          ∂ intervalMeasure 1)
        ≤ ell * negativePartEnergy u t

/-- The weak formulation, the cancellation, and the reaction bound give
`(1/2) E'(t) ≤ ell E(t)`. -/
theorem negativePart_half_energy_deriv_le
    {p : CM2Params} {T ell : ℝ}
    {u : ℝ → intervalDomainPoint → ℝ} {E' : ℝ → ℝ}
    (H : NegativePartEnergyEstimateData p T u ell E')
    {t : ℝ} (ht : 0 < t) (htT : t ≤ T) :
    (1 / 2 : ℝ) * E' t ≤ ell * negativePartEnergy u t := by
  have htest := negativePartWeakTestIdentityAt_of_weak
    H.weak ht htT
  have hchem_neg :
      (∫ x,
        truncatedChemFluxLifted p (u t) x
          * deriv (negativePartTest u t) x
        ∂ intervalMeasure 1) = 0 := by
    refine truncatedChemFluxLifted_mul_negDeriv_integral_eq_zero
      (p := p) (w := u t)
      (duNeg := fun x => deriv (negativePartTest u t) x) ?_
    filter_upwards [H.neg_deriv_zero_on_pos t ht htT] with x hx hpos
    change deriv (-negativePartLift (u t)) x = 0
    rw [deriv.neg]
    simp [hx hpos]
  have hmain :
      (1 / 2 : ℝ) * E' t + negativePartDissipation u t
        =
      (∫ x, truncatedLogisticLifted p (u t) x * negativePartTest u t x
          ∂ intervalMeasure 1) := by
    calc
      (1 / 2 : ℝ) * E' t + negativePartDissipation u t
          =
        (∫ x,
            intervalDomainLift
                (fun z : intervalDomainPoint =>
                  intervalDomain.timeDeriv u t z) x * negativePartTest u t x
            ∂ intervalMeasure 1)
          + (∫ x,
              deriv (intervalDomainLift (u t)) x * deriv (negativePartTest u t) x
              ∂ intervalMeasure 1) := by
            rw [H.time_chain t ht htT, H.diffusion_chain t ht htT]
      _ =
          p.χ₀ *
            (∫ x,
              truncatedChemFluxLifted p (u t) x
                * deriv (negativePartTest u t) x
              ∂ intervalMeasure 1)
          + (∫ x, truncatedLogisticLifted p (u t) x * negativePartTest u t x
              ∂ intervalMeasure 1) := htest
      _ = (∫ x, truncatedLogisticLifted p (u t) x * negativePartTest u t x
              ∂ intervalMeasure 1) := by
            simp [hchem_neg]
  calc
    (1 / 2 : ℝ) * E' t
        ≤ (1 / 2 : ℝ) * E' t + negativePartDissipation u t := by
          linarith [H.diffusion_nonneg t ht htT]
    _ = (∫ x, truncatedLogisticLifted p (u t) x * negativePartTest u t x
          ∂ intervalMeasure 1) := hmain
    _ ≤ ell * negativePartEnergy u t := H.reaction_bound t ht htT

/-- Full data needed to turn the weak negative-part estimate into the old
`NegativePartEnergyGronwallAvailable` interface. -/
structure NegativePartEnergyCoreData
    (p : CM2Params) {u₀ : intervalDomainPoint → ℝ}
    (DB : ConjugateMildExistenceData p u₀) where
  ell : ℝ
  hell_nonneg : 0 ≤ ell
  E' : ℝ → ℝ
  estimate :
    NegativePartEnergyEstimateData p DB.T
      (conjugatePicardLimit p u₀ DB.T) ell E'
  energy_cont :
    ContinuousOn
      (negativePartEnergy (conjugatePicardLimit p u₀ DB.T))
      (Set.Icc (0 : ℝ) DB.T)
  energy_has_deriv :
    ∀ t ∈ Set.Ico (0 : ℝ) DB.T,
      HasDerivWithinAt
        (negativePartEnergy (conjugatePicardLimit p u₀ DB.T))
        (E' t) (Set.Ici t) t
  energy_integrable :
    ∀ t, 0 < t → t ≤ DB.T →
      Integrable
        (fun x =>
          (negativePartLift (conjugatePicardLimit p u₀ DB.T t) x) ^ 2)
        (intervalMeasure 1)
  initial_vanishes :
    ∀ ε > 0, ∃ δ > 0, ∀ s, 0 < s → s < δ → s < DB.T →
      negativePartEnergy (conjugatePicardLimit p u₀ DB.T) s < ε
  zero_energy_to_pointwise_nonneg :
    ∀ t, 0 < t → t ≤ DB.T →
      negativePartEnergy (conjugatePicardLimit p u₀ DB.T) t = 0 →
        ∀ x : intervalDomainPoint,
          0 ≤ conjugatePicardLimit p u₀ DB.T t x

/-- The core data imply the old cron2 energy frontier. -/
theorem negativePartEnergyGronwallAvailable_of_coreData
    {p : CM2Params} {u₀ : intervalDomainPoint → ℝ}
    {DB : ConjugateMildExistenceData p u₀}
    (H : NegativePartEnergyCoreData p DB) :
    NegativePartEnergyGronwallAvailable p DB := by
  intro _hweak t ht htT x
  let u := conjugatePicardLimit p u₀ DB.T
  let E := negativePartEnergy u
  have hE_nonneg : ∀ τ, 0 < τ → τ ≤ DB.T → 0 ≤ E τ := by
    intro τ hτ0 hτT
    have _hint := H.energy_integrable τ hτ0 hτT
    have hnn :
        0 ≤ᵐ[intervalMeasure 1]
          fun x => (negativePartLift (u τ) x) ^ 2 :=
      Eventually.of_forall fun x => negativePartEnergyDensity_nonneg u τ x
    exact MeasureTheory.integral_nonneg_of_ae hnn
  have hderiv_le :
      ∀ τ, 0 < τ → τ < DB.T → H.E' τ ≤ (2 * H.ell) * E τ := by
    intro τ hτ0 hτT
    have hτTle : τ ≤ DB.T := le_of_lt hτT
    have hhalf := negativePart_half_energy_deriv_le
      H.estimate hτ0 hτTle
    nlinarith
  have hgron :
      ∃ K : ℝ, 0 ≤ K ∧
        ∀ s t, 0 < s → s ≤ t → t ≤ DB.T →
          E t ≤ E s * Real.exp (K * (t - s)) := by
    refine ⟨2 * H.ell, mul_nonneg (by norm_num) H.hell_nonneg, ?_⟩
    intro s τ hs hst hτT
    have hcont : ContinuousOn E (Set.Icc s τ) :=
      H.energy_cont.mono (by
        intro r hr
        exact ⟨le_trans (le_of_lt hs) hr.1, le_trans hr.2 hτT⟩)
    have hderiv :
        ∀ r ∈ Set.Ico s τ, HasDerivWithinAt E (H.E' r) (Set.Ici r) r := by
      intro r hr
      exact H.energy_has_deriv r
        ⟨le_of_lt (lt_of_lt_of_le hs hr.1), lt_of_lt_of_le hr.2 hτT⟩
    have hbound :
        ∀ r ∈ Set.Ico s τ, H.E' r ≤ (2 * H.ell) * E r := by
      intro r hr
      exact hderiv_le r (lt_of_lt_of_le hs hr.1) (lt_of_lt_of_le hr.2 hτT)
    exact ShenWork.Paper2.intervalDomainL2_gronwall_exp_of_diffIneq
      (E := E) (E' := H.E') (K := 2 * H.ell)
      hst hcont hderiv hbound
  have hE_zero_closed :
      ∀ τ, 0 < τ → τ ≤ DB.T → E τ = 0 :=
    energy_eq_zero_of_positive_time_gronwall hE_nonneg hgron H.initial_vanishes
  have hE_zero : E t = 0 := hE_zero_closed t ht htT
  exact H.zero_energy_to_pointwise_nonneg t ht htT hE_zero x

/-- Cron2 certificate constructor with the energy field discharged from the
proved cancellation/Gronwall core. -/
def bformCron2NegativePartHyp_of_concrete_truncated_energyCore
    {p : CM2Params} {u₀ : intervalDomainPoint → ℝ}
    {DB : ConjugateMildExistenceData p u₀}
    (DT : TruncatedConjugateMildExistenceData p u₀)
    (Hbridge : TruncatedConjugateLimitBridge p DB DT)
    (HmildWeak : TruncatedMildToWeakAvailable p DB)
    (Henergy : NegativePartEnergyCoreData p DB) :
    BFormCron2NegativePartHyp p DB :=
  bformCron2NegativePartHyp_of_concrete_truncated DT Hbridge HmildWeak
    (negativePartEnergyGronwallAvailable_of_coreData Henergy)

/-- Direct `negativePart_zero` theorem from the concrete truncated Picard data,
the mild-to-weak bridge, and the energy core. -/
theorem bform_negativePart_zero_of_concrete_truncated_energyCore
    {p : CM2Params} {u₀ : intervalDomainPoint → ℝ}
    {DB : ConjugateMildExistenceData p u₀}
    (DT : TruncatedConjugateMildExistenceData p u₀)
    (Hbridge : TruncatedConjugateLimitBridge p DB DT)
    (HmildWeak : TruncatedMildToWeakAvailable p DB)
    (Henergy : NegativePartEnergyCoreData p DB) :
    ∀ t, 0 < t → t ≤ DB.T → ∀ x : intervalDomainPoint,
      negativePart (conjugatePicardLimit p u₀ DB.T t x) = 0 := by
  exact bform_negativePart_zero
    (bformCron2NegativePartHyp_of_concrete_truncated_energyCore
      DT Hbridge HmildWeak Henergy)

end ShenWork.Paper2.BFormPositiveDatumNegPart
