import ShenWork.Paper2.IntervalBFormCron2NegativePartEnergy
import ShenWork.Paper2.IntervalBFormPdeUProducer
import ShenWork.Paper2.IntervalBFormDirectClassical

open Filter Topology Set

open ShenWork.IntervalDomain
  (intervalDomain intervalDomainLift intervalDomainPoint)
open ShenWork.IntervalConjugatePicard
  (ConjugateMildExistenceData conjugatePicardLimit
   conjugateMildSolutionData_of_data)
open ShenWork.IntervalMildToClassical
  (mildChemicalConcentration)
open ShenWork.IntervalNeumannFullKernel
  (intervalFullSemigroupOperator)
open ShenWork.Paper2

noncomputable section

namespace ShenWork.Paper2.BFormPositiveDatumLocal

open ShenWork.Paper2.BFormPositiveDatumNegPart

/-- Per-datum B-form package for the positive-initial-datum route.

The fields are the banked or explicitly carried pieces that are not yet all
generated by one constructor for boundary-vanishing data.  In particular, the
positivity proof below uses the cron2 negative-part route plus a heat lower
barrier, not a closed-domain paper-positive floor. -/
structure PositiveDatumBFormLocalComponents
    (p : CM2Params) (u₀ : intervalDomainPoint → ℝ) where
  DB : ConjugateMildExistenceData p u₀
  Hpde :
    ShenWork.IntervalBFormSpectral.HasBFormSpectralPdeAgreement p DB.T
      (conjugatePicardLimit p u₀ DB.T)
  DT : TruncatedConjugateMildExistenceData p u₀
  Hbridge : TruncatedConjugateLimitBridge p DB DT
  HmildWeak : TruncatedMildToWeakAvailable p DB
  Henergy : NegativePartEnergyCoreData p DB
  Cbarrier : ℝ
  heat_lower_barrier :
    ∀ t x, 0 < t → t < DB.T →
      Real.exp (-Cbarrier * t)
          * intervalFullSemigroupOperator t (intervalDomainLift u₀) x.1
        ≤ conjugatePicardLimit p u₀ DB.T t x
  regularity :
    intervalDomain.classicalRegularity DB.T
      (conjugatePicardLimit p u₀ DB.T)
      (mildChemicalConcentration p
        (conjugatePicardLimit p u₀ DB.T))
  hpde_v :
    ∀ t x, 0 < t → t < DB.T → x ∈ intervalDomain.inside →
      0 = intervalDomain.laplacian
            ((mildChemicalConcentration p
              (conjugatePicardLimit p u₀ DB.T)) t) x
          - p.μ *
            (mildChemicalConcentration p
              (conjugatePicardLimit p u₀ DB.T)) t x
          + p.ν *
            ((conjugatePicardLimit p u₀ DB.T) t x) ^ p.γ
  neumann :
    ∀ t x, 0 < t → t < DB.T → x ∈ intervalDomain.boundary →
      intervalDomain.normalDeriv
          ((conjugatePicardLimit p u₀ DB.T) t) x = 0 ∧
        intervalDomain.normalDeriv
          ((mildChemicalConcentration p
            (conjugatePicardLimit p u₀ DB.T)) t) x = 0

def PositiveDatumBFormLocalComponents.negativePart_zero
    {p : CM2Params} {u₀ : intervalDomainPoint → ℝ}
    (K : PositiveDatumBFormLocalComponents p u₀) :
    ∀ t, 0 < t → t ≤ K.DB.T → ∀ x : intervalDomainPoint,
      negativePart (conjugatePicardLimit p u₀ K.DB.T t x) = 0 :=
  bform_negativePart_zero_of_concrete_truncated_energyCore
    K.DT K.Hbridge K.HmildWeak K.Henergy

def PositiveDatumBFormLocalComponents.route
    {p : CM2Params} {u₀ : intervalDomainPoint → ℝ}
    (K : PositiveDatumBFormLocalComponents p u₀)
    (hu₀ : PositiveInitialDatum intervalDomain u₀) :
    BFormNegativePartPositivityRoute p K.DB where
  datum := hu₀
  negativePart_zero := K.negativePart_zero
  strictPos :=
    bform_strictPos_of_semigroup_lower_barrier
      (C := K.Cbarrier)
      (positiveInitialDatum_intervalDomainLift_continuousOn hu₀)
      (positiveInitialDatum_intervalDomainLift_nonneg hu₀)
      (positiveInitialDatum_intervalDomainLift_pos_somewhere hu₀)
      K.heat_lower_barrier
  hpde_u :=
    ShenWork.IntervalConjugatePicard.intervalConjugateMildSolution_pde_u_from_picard_data_and_spectral
      K.DB K.Hpde

theorem PositiveDatumBFormLocalComponents.isClassicalSolution
    {p : CM2Params} {u₀ : intervalDomainPoint → ℝ}
    (K : PositiveDatumBFormLocalComponents p u₀)
    (hu₀ : PositiveInitialDatum intervalDomain u₀) :
    IsPaper2ClassicalSolution intervalDomain p K.DB.T
      (conjugatePicardLimit p u₀ K.DB.T)
      (mildChemicalConcentration p
        (conjugatePicardLimit p u₀ K.DB.T)) := by
  let R := K.route hu₀
  refine IsPaper2ClassicalSolution.of_components K.DB.hT
    K.regularity R.strictPos ?_ R.hpde_u K.hpde_v K.neumann
  intro t x ht htT
  exact ShenWork.IntervalMildToClassical.mildChemical_nonneg
    (T := K.DB.T) p
    (u := conjugatePicardLimit p u₀ K.DB.T)
    (conjugateMildSolutionData_of_data K.DB).hnonneg
    (conjugateMildSolutionData_of_data K.DB).hcont
    ht (le_of_lt htT) x

theorem PositiveDatumBFormLocalComponents.localClassicalSolution
    {p : CM2Params} {u₀ : intervalDomainPoint → ℝ}
    (K : PositiveDatumBFormLocalComponents p u₀)
    (hu₀ : PositiveInitialDatum intervalDomain u₀) :
    ∃ Tmax > 0, ∃ u v : ℝ → intervalDomainPoint → ℝ,
      IsPaper2ClassicalSolution intervalDomain p Tmax u v ∧
      InitialTrace intervalDomain u₀ u := by
  refine ⟨K.DB.T, K.DB.hT,
    conjugatePicardLimit p u₀ K.DB.T,
    mildChemicalConcentration p (conjugatePicardLimit p u₀ K.DB.T), ?_⟩
  exact ⟨K.isClassicalSolution hu₀,
    ShenWork.Paper2.BFormInitialTrace.conjugatePicardLimit_initialTrace_of_conjugate_data
      p hu₀.admissible.2 K.DB⟩

/-- The remaining local-existence plumbing, stated per datum. -/
def PositiveDatumBFormLocalHyp (p : CM2Params) : Prop :=
  ∀ u₀ : intervalDomainPoint → ℝ,
    PositiveInitialDatum intervalDomain u₀ →
      Nonempty (PositiveDatumBFormLocalComponents p u₀)

/-- Local classical existence for all positive initial data from the B-form
components.  This is the `hlocal` argument required by the general-chi B-form
headline. -/
theorem positiveDatum_localExistence_of_BForm
    {p : CM2Params}
    (hBForm : PositiveDatumBFormLocalHyp p) :
    ∀ u₀ : intervalDomainPoint → ℝ,
      PositiveInitialDatum intervalDomain u₀ →
        ∃ Tmax > 0, ∃ u v : ℝ → intervalDomainPoint → ℝ,
          IsPaper2ClassicalSolution intervalDomain p Tmax u v ∧
          InitialTrace intervalDomain u₀ u := by
  intro u₀ hu₀
  obtain ⟨K⟩ := hBForm u₀ hu₀
  exact K.localClassicalSolution hu₀

theorem realize_of_positiveDatum_localExistence_of_BForm
    (p : CM2Params) (hχ : p.χ₀ ≤ 0) (ha : 0 < p.a) (hb : 0 < p.b)
    (hγ_ge_one : 1 ≤ p.γ)
    (hBForm : PositiveDatumBFormLocalHyp p) :
    ∀ u₀ : intervalDomain.Point → ℝ,
      PositiveInitialDatum intervalDomain u₀ →
    ∀ _hbdd : BddAbove
        (ShenWork.IntervalDomainExistence.reachableClassicalHorizonSet p u₀),
      ∃ u v : ℝ → intervalDomain.Point → ℝ,
        IsPaper2ClassicalSolution intervalDomain p
          (ShenWork.IntervalDomainExistence.finiteMaximalReachableHorizon
            p u₀) u v ∧
        InitialTrace intervalDomain u₀ u :=
  realize_of_regime_gammaGeOne p hχ ha hb hγ_ge_one
    (positiveDatum_localExistence_of_BForm hBForm)

/-- General-chi B-form headline with `hlocal` discharged by the positive-datum
B-form component package.  The remaining assumptions are the explicit B-form
local plumbing above and the uniform-local-existence continuation input. -/
theorem paper2_theorem_1_1_general_chi_bform
    (p : CM2Params) (hχ : p.χ₀ ≤ 0) (ha : 0 < p.a) (hb : 0 < p.b)
    (hγ_ge_one : 1 ≤ p.γ)
    (hBForm : PositiveDatumBFormLocalHyp p)
    (hUniform : IntervalDomainUniformLocalExistence p) :
    Theorem_1_1 intervalDomain p :=
  ShenWork.Paper2.BFormDirectClassical.paper2_theorem_1_1_general_chi_bform
    p hχ ha hb hγ_ge_one
    (positiveDatum_localExistence_of_BForm hBForm) hUniform

end ShenWork.Paper2.BFormPositiveDatumLocal
