import ShenWork.Paper2.IntervalTruncatedLeftProfile
import ShenWork.Paper2.IntervalTruncatedPositiveTimeGradientAtoms

open MeasureTheory Set intervalIntegral
open scoped BigOperators Topology Real

#check intervalIntegral.integral_mono_ae_restrict
#check intervalIntegral.integral_mono_on
#check intervalIntegral.integral_of_le
#check intervalIntegral.integral_comp_add_right
#check intervalIntegral.integral_comp_sub_left
#check intervalIntegral.integral_mono_interval
#check intervalIntegral.integral_nonneg_of_ae
#check intervalIntegral.integral_nonneg
#check intervalIntegral.integral_add_adjacent_intervals
#check IntervalIntegrable.mono_fun'
#check IntervalIntegrable.mono_fun
#check IntervalIntegrable.mono_measure
#check IntervalIntegrable.const_mul
#check IntervalIntegrable.mul_const
#check ShenWork.IntervalGradDuhamelBound.intervalIntegrable_sub_rpow_neg_half
#check ShenWork.IntervalGradDuhamelBound.integral_sub_rpow_neg_half
#check ShenWork.IntervalNeumannFullKernel.intervalFullCoupledDuhamel_grad_integrand_pointwise_bound
#check intervalFullCoupledDuhamel_grad_integrand_pointwise_bound
#check le_of_tendsto
#check Filter.Tendsto.const_mul
#check Filter.Tendsto.add
#check Real.continuous_sqrt
#check continuous_sqrt
#check continuousAt_id
#check tendsto_const_nhds
#check tendsto_nhdsWithin_iff
#check Filter.Tendsto.comp
#check Filter.Tendsto.congr'
#check Metric.tendsto_nhds
#check IntervalIntegrable.norm
#check IntervalIntegrable.re
#check Complex.reCLM
#check ContinuousLinearMap.intervalIntegrable_comp
#check ContinuousLinearMap.compL
#check IntervalIntegrable.of_norm
#check intervalIntegral.integral_ofReal
#check MeasureTheory.Integrable.ofReal
#check MeasureTheory.Integrable.comp_measurable
#check IntervalIntegrable.comp_mul_left
#check IntervalIntegrable.comp_mul_right
#check IntervalIntegrable.comp_div
#check IntervalIntegrable.comp_div'
#check IntervalIntegrable.comp_sub_left
#check IntervalIntegrable.comp_add_right
#check IntervalIntegrable.comp_add_left
#check IntervalIntegrable.trans
#check IntervalIntegrable.symm
#check IntervalIntegrable.mul_continuousOn
#check ContinuousOn.mul
#check ContinuousAt.rpow_const
#check ContinuousOn.rpow_const
#check intervalIntegral.intervalIntegrable_rpow'
