/-
Copyright (c) 2026 Xiang Huang. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Xiang Huang
-/
import Mathlib.Analysis.SpecialFunctions.Exp
import Mathlib.MeasureTheory.Integral.Bochner.Basic
import Mathlib.MeasureTheory.Group.Integral
import Mathlib.MeasureTheory.Measure.Haar.Unique
import Mathlib.Order.Filter.Basic
import Mathlib.Tactic.Linarith
import Mathlib.Tactic.Ring

/-!
# Dispersal kernels and exponential modes

For the convolution convention

`(K ⋆ f)(x) = ∫ y, K (x - y) * f y`,

the exponential tail `x ↦ exp (-μx)` is an eigenfunction with eigenvalue

`M_K(μ) = ∫ z, K z * exp (μz)`.

No positivity or normalization hypothesis is needed for the identity itself.
Those assumptions enter only when the identity is used as a population
comparison estimate.
-/

open Filter MeasureTheory Topology

noncomputable section

namespace ShenWork.Analysis

/-- The whole-line dispersal operator with the `K (x - y)` convention. -/
def dispersal (K f : ℝ → ℝ) (x : ℝ) : ℝ :=
  ∫ y, K (x - y) * f y

/-- The exponential tail used in linear-determinacy arguments. -/
def exponentialTail (μ x : ℝ) : ℝ :=
  Real.exp (-μ * x)

/-- The bilateral moment-generating integral of a dispersal kernel. -/
def kernelMoment (K : ℝ → ℝ) (μ : ℝ) : ℝ :=
  ∫ z, K z * Real.exp (μ * z)

/-- Translation puts the dispersal integral into the fixed-kernel form
`∫ z, K z * f (x - z)`. -/
theorem dispersal_eq_shift (K f : ℝ → ℝ) (x : ℝ) :
    dispersal K f x = ∫ z, K z * f (x - z) := by
  unfold dispersal
  have h :=
    integral_sub_left_eq_self
      (fun z => K z * f (x - z)) (volume : Measure ℝ) x
  simp only [sub_sub_cancel] at h
  exact h

/-- Constants pull through the dispersal operator. -/
theorem dispersal_const_mul (K f : ℝ → ℝ) (a x : ℝ) :
    dispersal K (fun y => a * f y) x = a * dispersal K f x := by
  unfold dispersal
  rw [show (fun y => K (x - y) * (a * f y)) =
      fun y => a * (K (x - y) * f y) by
    funext y
    ring]
  rw [integral_const_mul]

/-- The exponential tail is an exact eigenfunction of dispersal. -/
theorem dispersal_exponentialTail (K : ℝ → ℝ) (μ x : ℝ) :
    dispersal K (exponentialTail μ) x =
      kernelMoment K μ * exponentialTail μ x := by
  rw [dispersal_eq_shift]
  unfold exponentialTail kernelMoment
  rw [show (fun z => K z * Real.exp (-μ * (x - z))) =
      fun z => Real.exp (-μ * x) * (K z * Real.exp (μ * z)) by
    funext z
    rw [show -μ * (x - z) = -μ * x + μ * z by ring, Real.exp_add]
    ring]
  rw [integral_const_mul]
  ring

/-- One linear growth-and-dispersal step. -/
def linearDispersalStep (K : ℝ → ℝ) (growth : ℝ)
    (f : ℝ → ℝ) (x : ℝ) : ℝ :=
  growth * dispersal K f x

/-- The eigenvalue of one linear growth-and-dispersal step is
`growth * kernelMoment K μ`. -/
theorem linearDispersalStep_exponentialTail
    (K : ℝ → ℝ) (growth μ x : ℝ) :
    linearDispersalStep K growth (exponentialTail μ) x =
      (growth * kernelMoment K μ) * exponentialTail μ x := by
  rw [linearDispersalStep, dispersal_exponentialTail]
  ring

/-- The explicit exponential orbit generated by a moment eigenvalue. -/
def exponentialOrbit
    (amplitude growth moment μ : ℝ) (n : ℕ) (x : ℝ) : ℝ :=
  amplitude * (growth * moment) ^ n * exponentialTail μ x

@[simp]
theorem exponentialOrbit_zero
    (amplitude growth moment μ x : ℝ) :
    exponentialOrbit amplitude growth moment μ 0 x =
      amplitude * exponentialTail μ x := by
  simp [exponentialOrbit]

/-- The explicit exponential orbit satisfies the linear
growth-and-dispersal recursion. -/
theorem exponentialOrbit_succ
    (K : ℝ → ℝ) (amplitude growth μ : ℝ) (n : ℕ) (x : ℝ) :
    exponentialOrbit amplitude growth (kernelMoment K μ) μ (n + 1) x =
      linearDispersalStep K growth
        (exponentialOrbit amplitude growth (kernelMoment K μ) μ n) x := by
  unfold exponentialOrbit linearDispersalStep
  rw [dispersal_const_mul, dispersal_exponentialTail, pow_succ]
  ring

/-- Along the frame `x = c n`, the exponential orbit is a geometric sequence
with ratio `(growth * moment) * exp (-μc)`. -/
theorem exponentialOrbit_movingFrame
    (amplitude growth moment μ c : ℝ) (n : ℕ) :
    exponentialOrbit amplitude growth moment μ n (c * (n : ℝ)) =
      amplitude * ((growth * moment) * Real.exp (-μ * c)) ^ n := by
  unfold exponentialOrbit exponentialTail
  have hexp :
      Real.exp (-μ * (c * (n : ℝ))) = Real.exp (-μ * c) ^ n := by
    rw [← Real.exp_nat_mul]
    congr 1
    ring
  rw [hexp, mul_pow]
  ring

/-- A nonnegative geometric moving-frame ratio below one forces extinction of
the corresponding exponential orbit along that frame. -/
theorem exponentialOrbit_movingFrame_tendsto_zero
    (amplitude growth moment μ c : ℝ)
    (hq0 : 0 ≤ (growth * moment) * Real.exp (-μ * c))
    (hq1 : (growth * moment) * Real.exp (-μ * c) < 1) :
    Tendsto
      (fun n : ℕ =>
        exponentialOrbit amplitude growth moment μ n (c * (n : ℝ)))
      atTop (𝓝 0) := by
  have hpow :
      Tendsto
        (fun n : ℕ => ((growth * moment) * Real.exp (-μ * c)) ^ n)
        atTop (𝓝 0) :=
    tendsto_pow_atTop_nhds_zero_of_lt_one hq0 hq1
  have hscaled := hpow.const_mul amplitude
  simpa [exponentialOrbit_movingFrame] using hscaled

/-- The variational speed inequality `log R / μ < c` is exactly the condition
that the moving-frame geometric ratio `R * exp (-μc)` is below one. -/
theorem movingFrame_ratio_lt_one_of_speed_gt
    {R μ c : ℝ} (hR : 0 < R) (hμ : 0 < μ)
    (hc : Real.log R / μ < c) :
    R * Real.exp (-μ * c) < 1 := by
  have hlog : Real.log R < μ * c := by
    simpa [mul_comm] using (div_lt_iff₀ hμ).mp hc
  have harg : -μ * c < -Real.log R := by
    linarith
  have hexp :
      Real.exp (-μ * c) < R⁻¹ := by
    have h := Real.exp_lt_exp.mpr harg
    rw [Real.exp_neg, Real.exp_log hR] at h
    exact h
  have hmul := mul_lt_mul_of_pos_left hexp hR
  simpa [ne_of_gt hR] using hmul

/-- The linear-determinacy conclusion for one fixed exponential weight. -/
theorem exponentialOrbit_tendsto_zero_of_speed_gt
    {amplitude growth moment μ c : ℝ}
    (hR : 0 < growth * moment) (hμ : 0 < μ)
    (hc : Real.log (growth * moment) / μ < c) :
    Tendsto
      (fun n : ℕ =>
        exponentialOrbit amplitude growth moment μ n (c * (n : ℝ)))
      atTop (𝓝 0) := by
  apply exponentialOrbit_movingFrame_tendsto_zero
  · exact mul_nonneg hR.le (Real.exp_pos _).le
  · exact movingFrame_ratio_lt_one_of_speed_gt hR hμ hc

section AxiomAudit

#print axioms dispersal_exponentialTail
#print axioms exponentialOrbit_succ
#print axioms exponentialOrbit_tendsto_zero_of_speed_gt

end AxiomAudit

end ShenWork.Analysis
