import ShenWork.PDE.ResolventEstimate
import Mathlib.Analysis.Analytic.Constructions
import Mathlib.Analysis.SpecialFunctions.ExpDeriv

/-!
# Coefficient analytic semigroup generated by the shifted interval Neumann operator

This file closes the concrete diagonal H3.1 subblock supplied by
`ResolventEstimate`: for the unit-interval Neumann spectrum and shift `ω ≥ 0`,
the sector resolvent estimate and nonnegative diagonal spectrum form a
certificate that generates the bounded analytic heat semigroup and the
parabolic smoothing estimate

`‖A e^{-tA} a‖₂ ≤ (1 / t) ‖a‖₂`.

This is intentionally a coefficient `ℓ²` theorem.  Mathlib does not currently
provide the unbounded closed-operator/resolvent-set API, Dunford contour
integrals, or the abstract sectorial-generation theorem needed to turn a bare
resolvent estimate into an operator-valued analytic `C₀` semigroup on the
physical `C¹`/fractional-domain spaces.  The frontier is therefore precise:
the diagonal unit-interval semigroup estimates below are proved; the abstract
closed-operator sectorial-generation bridge is still missing infrastructure.
-/

noncomputable section

namespace ShenWork.PDE.AnalyticSemigroupGen

open ShenWork.Paper3
open ShenWork.PDE.ResolventEstimate

/-! ### Diagonal complex-time semigroup -/

/-- Real-time diagonal heat multiplier for `A = -Δ_N + ω`. -/
def shiftedNeumannHeatCoeff (ω t : ℝ) (a : ℕ → ℂ) (n : ℕ) : ℂ :=
  (Real.exp (-(shiftedNeumannEigenvalue ω n * t)) : ℂ) * a n

/-- Complex-time diagonal heat multiplier for `A = -Δ_N + ω`. -/
def shiftedNeumannAnalyticHeatCoeff (ω : ℝ) (z : ℂ)
    (a : ℕ → ℂ) (n : ℕ) : ℂ :=
  Complex.exp (-((shiftedNeumannEigenvalue ω n : ℂ) * z)) * a n

/-- Coefficient form of `A e^{-tA}`. -/
def shiftedNeumannGeneratorHeatCoeff (ω t : ℝ)
    (a : ℕ → ℂ) (n : ℕ) : ℂ :=
  (shiftedNeumannEigenvalue ω n : ℂ) *
    shiftedNeumannHeatCoeff ω t a n

theorem shiftedNeumannAnalyticHeatCoeff_zero
    (ω : ℝ) (a : ℕ → ℂ) :
    shiftedNeumannAnalyticHeatCoeff ω 0 a = a := by
  funext n
  simp [shiftedNeumannAnalyticHeatCoeff]

theorem shiftedNeumannAnalyticHeatCoeff_add
    (ω : ℝ) (z w : ℂ) (a : ℕ → ℂ) :
    shiftedNeumannAnalyticHeatCoeff ω (z + w) a =
      shiftedNeumannAnalyticHeatCoeff ω z
        (shiftedNeumannAnalyticHeatCoeff ω w a) := by
  funext n
  change
    Complex.exp
        (-((shiftedNeumannEigenvalue ω n : ℂ) * (z + w))) * a n =
      Complex.exp (-((shiftedNeumannEigenvalue ω n : ℂ) * z)) *
        (Complex.exp (-((shiftedNeumannEigenvalue ω n : ℂ) * w)) * a n)
  rw [show
      -((shiftedNeumannEigenvalue ω n : ℂ) * (z + w)) =
        -((shiftedNeumannEigenvalue ω n : ℂ) * z) +
          -((shiftedNeumannEigenvalue ω n : ℂ) * w) by ring,
    Complex.exp_add]
  ring

theorem shiftedNeumannAnalyticHeatCoeff_analyticAt
    (ω : ℝ) (a : ℕ → ℂ) (n : ℕ) (z : ℂ) :
    AnalyticAt ℂ
      (fun ζ : ℂ => shiftedNeumannAnalyticHeatCoeff ω ζ a n) z := by
  unfold shiftedNeumannAnalyticHeatCoeff
  fun_prop

theorem shiftedNeumannAnalyticHeatCoeff_analyticOn_rightHalfPlane
    (ω : ℝ) (a : ℕ → ℂ) (n : ℕ) :
    AnalyticOn ℂ
      (fun z : ℂ => shiftedNeumannAnalyticHeatCoeff ω z a n)
      {z : ℂ | 0 < z.re} := by
  intro z _hz
  exact (shiftedNeumannAnalyticHeatCoeff_analyticAt ω a n z).analyticWithinAt

/-! ### Boundedness on the right half-plane -/

lemma complex_exp_neg_real_mul_norm_le_one {r : ℝ} (hr : 0 ≤ r)
    {z : ℂ} (hz : 0 ≤ z.re) :
    ‖Complex.exp (-((r : ℂ) * z))‖ ≤ 1 := by
  rw [Complex.norm_exp]
  apply Real.exp_le_one_iff.mpr
  have hre : (-((r : ℂ) * z)).re = -(r * z.re) := by
    simp [Complex.mul_re]
  rw [hre]
  exact neg_nonpos.mpr (mul_nonneg hr hz)

theorem shiftedNeumannAnalyticHeatCoeff_sq_le
    {ω : ℝ} (hω : 0 ≤ ω) {z : ℂ} (hz : 0 ≤ z.re)
    (a : ℕ → ℂ) (n : ℕ) :
    ‖shiftedNeumannAnalyticHeatCoeff ω z a n‖ ^ 2 ≤ ‖a n‖ ^ 2 := by
  have hr : 0 ≤ shiftedNeumannEigenvalue ω n :=
    shiftedNeumannEigenvalue_nonneg hω n
  have hmult :
      ‖Complex.exp (-((shiftedNeumannEigenvalue ω n : ℂ) * z))‖ ≤ 1 :=
    complex_exp_neg_real_mul_norm_le_one hr hz
  have hmul :
      ‖Complex.exp (-((shiftedNeumannEigenvalue ω n : ℂ) * z))‖ *
          ‖a n‖ ≤
        1 * ‖a n‖ :=
    mul_le_mul_of_nonneg_right hmult (norm_nonneg (a n))
  calc
    ‖shiftedNeumannAnalyticHeatCoeff ω z a n‖ ^ 2
        =
          (‖Complex.exp (-((shiftedNeumannEigenvalue ω n : ℂ) * z))‖ *
            ‖a n‖) ^ 2 := by
          rw [shiftedNeumannAnalyticHeatCoeff, norm_mul]
    _ ≤ (1 * ‖a n‖) ^ 2 := by
          exact
            (sq_le_sq₀
              (mul_nonneg (norm_nonneg _) (norm_nonneg _))
              (mul_nonneg zero_le_one (norm_nonneg _))).mpr hmul
    _ = ‖a n‖ ^ 2 := by ring

theorem shiftedNeumannAnalyticHeatCoeff_l2_summable
    {ω : ℝ} (hω : 0 ≤ ω) {z : ℂ} (hz : 0 ≤ z.re)
    {a : ℕ → ℂ} (ha : Summable fun n : ℕ => ‖a n‖ ^ 2) :
    Summable fun n : ℕ =>
      ‖shiftedNeumannAnalyticHeatCoeff ω z a n‖ ^ 2 := by
  apply Summable.of_nonneg_of_le
    (fun n => sq_nonneg _)
    ?_
    ha
  intro n
  exact shiftedNeumannAnalyticHeatCoeff_sq_le hω hz a n

/-- Boundedness of the complex-time heat semigroup on the closed right
half-plane, in coefficient `ℓ²` energy form. -/
theorem shiftedNeumannAnalyticHeatCoeff_l2_energy_le
    {ω : ℝ} (hω : 0 ≤ ω) {z : ℂ} (hz : 0 ≤ z.re)
    {a : ℕ → ℂ} (ha : Summable fun n : ℕ => ‖a n‖ ^ 2) :
    coeffL2Energy (shiftedNeumannAnalyticHeatCoeff ω z a) ≤
      coeffL2Energy a := by
  have hs :=
    shiftedNeumannAnalyticHeatCoeff_l2_summable hω hz ha
  have hle :
      ∀ n : ℕ,
        ‖shiftedNeumannAnalyticHeatCoeff ω z a n‖ ^ 2 ≤
          ‖a n‖ ^ 2 :=
    shiftedNeumannAnalyticHeatCoeff_sq_le hω hz a
  have htsum := hs.tsum_le_tsum hle ha
  simpa [coeffL2Energy] using htsum

/-- Boundedness of the complex-time heat semigroup on the closed right
half-plane, in coefficient `ℓ²` norm form. -/
theorem shiftedNeumannAnalyticHeatCoeff_l2_norm_le
    {ω : ℝ} (hω : 0 ≤ ω) {z : ℂ} (hz : 0 ≤ z.re)
    {a : ℕ → ℂ} (ha : Summable fun n : ℕ => ‖a n‖ ^ 2) :
    coeffL2Norm (shiftedNeumannAnalyticHeatCoeff ω z a) ≤
      coeffL2Norm a := by
  have henergy :=
    shiftedNeumannAnalyticHeatCoeff_l2_energy_le hω hz ha
  exact Real.sqrt_le_sqrt henergy

/-! ### The `A e^{-tA}` bound -/

lemma real_mul_exp_neg_le_one (y : ℝ) :
    y * Real.exp (-y) ≤ 1 := by
  have hy_le_exp : y ≤ Real.exp y := by
    have h := Real.add_one_le_exp y
    linarith
  have hinv_nonneg : 0 ≤ (Real.exp y)⁻¹ :=
    inv_nonneg.mpr (Real.exp_nonneg y)
  have h :=
    mul_le_mul_of_nonneg_right hy_le_exp hinv_nonneg
  simpa [Real.exp_neg, mul_inv_cancel₀ (ne_of_gt (Real.exp_pos y))] using h

lemma real_mul_exp_neg_mul_le_inv {r t : ℝ} (ht : 0 < t) :
    r * Real.exp (-(r * t)) ≤ 1 / t := by
  have hy :=
    real_mul_exp_neg_le_one (t * r)
  have hscale_nonneg : 0 ≤ 1 / t :=
    div_nonneg zero_le_one ht.le
  have hscaled :
      (1 / t) * ((t * r) * Real.exp (-(t * r))) ≤
        (1 / t) * 1 :=
    mul_le_mul_of_nonneg_left hy hscale_nonneg
  calc
    r * Real.exp (-(r * t))
        = r * Real.exp (-(t * r)) := by
          rw [show -(r * t) = -(t * r) by ring]
    _ = (1 / t) * ((t * r) * Real.exp (-(t * r))) := by
          field_simp [ne_of_gt ht]
    _ ≤ (1 / t) * 1 := hscaled
    _ = 1 / t := by ring

theorem shiftedNeumannGeneratorHeatCoeff_sq_le
    {ω t : ℝ} (hω : 0 ≤ ω) (ht : 0 < t)
    (a : ℕ → ℂ) (n : ℕ) :
    ‖shiftedNeumannGeneratorHeatCoeff ω t a n‖ ^ 2 ≤
      ((1 : ℝ) / t) ^ 2 * ‖a n‖ ^ 2 := by
  set r := shiftedNeumannEigenvalue ω n with hrdef
  have hr : 0 ≤ r := by
    simpa [hrdef] using shiftedNeumannEigenvalue_nonneg hω n
  have hcoef : r * Real.exp (-(r * t)) ≤ (1 : ℝ) / t :=
    real_mul_exp_neg_mul_le_inv ht
  have hcoef_nonneg : 0 ≤ r * Real.exp (-(r * t)) :=
    mul_nonneg hr (Real.exp_nonneg _)
  have hinv_nonneg : 0 ≤ (1 : ℝ) / t :=
    div_nonneg zero_le_one ht.le
  have hmul :
      r * Real.exp (-(r * t)) * ‖a n‖ ≤
        ((1 : ℝ) / t) * ‖a n‖ :=
    mul_le_mul_of_nonneg_right hcoef (norm_nonneg (a n))
  calc
    ‖shiftedNeumannGeneratorHeatCoeff ω t a n‖ ^ 2
        =
          (‖(r : ℂ)‖ *
            (‖(Real.exp (-(r * t)) : ℂ)‖ * ‖a n‖)) ^ 2 := by
          rw [shiftedNeumannGeneratorHeatCoeff, shiftedNeumannHeatCoeff,
            ← hrdef, norm_mul, norm_mul]
    _ =
          (r * Real.exp (-(r * t)) * ‖a n‖) ^ 2 := by
          rw [Complex.norm_of_nonneg hr,
            Complex.norm_of_nonneg (Real.exp_nonneg (-(r * t)))]
          ring
    _ ≤ (((1 : ℝ) / t) * ‖a n‖) ^ 2 := by
          exact
            (sq_le_sq₀
              (mul_nonneg hcoef_nonneg (norm_nonneg _))
              (mul_nonneg hinv_nonneg (norm_nonneg _))).mpr hmul
    _ = ((1 : ℝ) / t) ^ 2 * ‖a n‖ ^ 2 := by ring

theorem shiftedNeumannGeneratorHeatCoeff_l2_summable
    {ω t : ℝ} (hω : 0 ≤ ω) (ht : 0 < t)
    {a : ℕ → ℂ} (ha : Summable fun n : ℕ => ‖a n‖ ^ 2) :
    Summable fun n : ℕ =>
      ‖shiftedNeumannGeneratorHeatCoeff ω t a n‖ ^ 2 := by
  apply Summable.of_nonneg_of_le
    (fun n => sq_nonneg _)
    ?_
    (ha.mul_left (((1 : ℝ) / t) ^ 2))
  intro n
  exact shiftedNeumannGeneratorHeatCoeff_sq_le hω ht a n

/-- Coefficient `ℓ²` energy form of `‖A e^{-tA}‖ ≤ 1 / t`. -/
theorem shiftedNeumannGeneratorHeatCoeff_l2_energy_le
    {ω t : ℝ} (hω : 0 ≤ ω) (ht : 0 < t)
    {a : ℕ → ℂ} (ha : Summable fun n : ℕ => ‖a n‖ ^ 2) :
    coeffL2Energy (shiftedNeumannGeneratorHeatCoeff ω t a) ≤
      ((1 : ℝ) / t) ^ 2 * coeffL2Energy a := by
  have hs :=
    shiftedNeumannGeneratorHeatCoeff_l2_summable hω ht ha
  have hmajor :
      Summable fun n : ℕ =>
        ((1 : ℝ) / t) ^ 2 * ‖a n‖ ^ 2 :=
    ha.mul_left (((1 : ℝ) / t) ^ 2)
  have hle :
      ∀ n : ℕ,
        ‖shiftedNeumannGeneratorHeatCoeff ω t a n‖ ^ 2 ≤
          ((1 : ℝ) / t) ^ 2 * ‖a n‖ ^ 2 :=
    shiftedNeumannGeneratorHeatCoeff_sq_le hω ht a
  have htsum := hs.tsum_le_tsum hle hmajor
  simpa [coeffL2Energy, ha.tsum_mul_left] using htsum

/-- Coefficient `ℓ²` norm form of `‖A e^{-tA}‖ ≤ 1 / t`. -/
theorem shiftedNeumannGeneratorHeatCoeff_l2_norm_le
    {ω t : ℝ} (hω : 0 ≤ ω) (ht : 0 < t)
    {a : ℕ → ℂ} (ha : Summable fun n : ℕ => ‖a n‖ ^ 2) :
    coeffL2Norm (shiftedNeumannGeneratorHeatCoeff ω t a) ≤
      ((1 : ℝ) / t) * coeffL2Norm a := by
  have henergy :=
    shiftedNeumannGeneratorHeatCoeff_l2_energy_le hω ht ha
  have hsqrt := Real.sqrt_le_sqrt henergy
  have hfactor_nonneg : 0 ≤ (1 : ℝ) / t :=
    div_nonneg zero_le_one ht.le
  calc
    coeffL2Norm (shiftedNeumannGeneratorHeatCoeff ω t a)
        = Real.sqrt
          (coeffL2Energy (shiftedNeumannGeneratorHeatCoeff ω t a)) := rfl
    _ ≤ Real.sqrt (((1 : ℝ) / t) ^ 2 * coeffL2Energy a) := hsqrt
    _ = ((1 : ℝ) / t) * coeffL2Norm a := by
          rw [Real.sqrt_mul (sq_nonneg ((1 : ℝ) / t))]
          rw [Real.sqrt_sq hfactor_nonneg]
          rfl

/-! ### Spectral-bound exponential decay -/

lemma shiftedNeumannEigenvalue_ge_shift (ω : ℝ) (n : ℕ) :
    ω ≤ shiftedNeumannEigenvalue ω n := by
  unfold shiftedNeumannEigenvalue
  have hspec := unitIntervalNeumannSpectrum_eigenvalue_nonneg n
  linarith

/-- Pointwise shifted heat coefficient decay from the spectral bound `ω`. -/
theorem shiftedNeumannHeatCoeff_sq_le_exp_shift
    {ω t : ℝ} (ht : 0 ≤ t) (a : ℕ → ℂ) (n : ℕ) :
    ‖shiftedNeumannHeatCoeff ω t a n‖ ^ 2 ≤
      (Real.exp (-(ω * t))) ^ 2 * ‖a n‖ ^ 2 := by
  set r := shiftedNeumannEigenvalue ω n with hrdef
  have hge : ω ≤ r := by
    simpa [hrdef] using shiftedNeumannEigenvalue_ge_shift ω n
  have hmul : -(r * t) ≤ -(ω * t) := by
    have hrt : ω * t ≤ r * t := mul_le_mul_of_nonneg_right hge ht
    linarith
  have hexp_le : Real.exp (-(r * t)) ≤ Real.exp (-(ω * t)) :=
    Real.exp_le_exp.mpr hmul
  have hexp_nonneg : 0 ≤ Real.exp (-(r * t)) := Real.exp_nonneg _
  have homega_nonneg : 0 ≤ Real.exp (-(ω * t)) := Real.exp_nonneg _
  have hnorm_nonneg : 0 ≤ ‖a n‖ := norm_nonneg _
  have hle :
      Real.exp (-(r * t)) * ‖a n‖ ≤
        Real.exp (-(ω * t)) * ‖a n‖ :=
    mul_le_mul_of_nonneg_right hexp_le hnorm_nonneg
  calc
    ‖shiftedNeumannHeatCoeff ω t a n‖ ^ 2
        =
          (Real.exp (-(r * t)) * ‖a n‖) ^ 2 := by
            rw [shiftedNeumannHeatCoeff, ← hrdef, norm_mul,
              Complex.norm_of_nonneg hexp_nonneg]
    _ ≤ (Real.exp (-(ω * t)) * ‖a n‖) ^ 2 := by
            exact
              (sq_le_sq₀
                (mul_nonneg hexp_nonneg hnorm_nonneg)
                (mul_nonneg homega_nonneg hnorm_nonneg)).mpr hle
    _ = (Real.exp (-(ω * t))) ^ 2 * ‖a n‖ ^ 2 := by
            ring

/-- Shifted heat preserves square-summability under the spectral-bound decay
estimate. -/
theorem shiftedNeumannHeatCoeff_l2_summable_of_exp_shift
    {ω t : ℝ} (ht : 0 ≤ t) {a : ℕ → ℂ}
    (ha : Summable fun n : ℕ => ‖a n‖ ^ 2) :
    Summable fun n : ℕ => ‖shiftedNeumannHeatCoeff ω t a n‖ ^ 2 := by
  apply Summable.of_nonneg_of_le
    (fun n => sq_nonneg _)
    ?_
    (ha.mul_left ((Real.exp (-(ω * t))) ^ 2))
  intro n
  exact shiftedNeumannHeatCoeff_sq_le_exp_shift ht a n

/-- Coefficient `ℓ²` energy decay for the shifted Neumann heat semigroup. -/
theorem shiftedNeumannHeatCoeff_l2_energy_decay
    {ω t : ℝ} (ht : 0 ≤ t) {a : ℕ → ℂ}
    (ha : Summable fun n : ℕ => ‖a n‖ ^ 2) :
    coeffL2Energy (shiftedNeumannHeatCoeff ω t a) ≤
      (Real.exp (-(ω * t))) ^ 2 * coeffL2Energy a := by
  have hs :=
    shiftedNeumannHeatCoeff_l2_summable_of_exp_shift
      (ω := ω) ht ha
  have hmajor :
      Summable fun n : ℕ =>
        (Real.exp (-(ω * t))) ^ 2 * ‖a n‖ ^ 2 :=
    ha.mul_left ((Real.exp (-(ω * t))) ^ 2)
  have hle :
      ∀ n : ℕ,
        ‖shiftedNeumannHeatCoeff ω t a n‖ ^ 2 ≤
          (Real.exp (-(ω * t))) ^ 2 * ‖a n‖ ^ 2 :=
    shiftedNeumannHeatCoeff_sq_le_exp_shift ht a
  have htsum := hs.tsum_le_tsum hle hmajor
  simpa [coeffL2Energy, ha.tsum_mul_left] using htsum

/-- Coefficient `ℓ²` norm decay for the shifted Neumann heat semigroup. -/
theorem shiftedNeumannHeatCoeff_l2_norm_decay
    {ω t : ℝ} (ht : 0 ≤ t) {a : ℕ → ℂ}
    (ha : Summable fun n : ℕ => ‖a n‖ ^ 2) :
    coeffL2Norm (shiftedNeumannHeatCoeff ω t a) ≤
      Real.exp (-(ω * t)) * coeffL2Norm a := by
  have henergy :=
    shiftedNeumannHeatCoeff_l2_energy_decay (ω := ω) ht ha
  have hsqrt := Real.sqrt_le_sqrt henergy
  have hfactor_nonneg : 0 ≤ Real.exp (-(ω * t)) := Real.exp_nonneg _
  calc
    coeffL2Norm (shiftedNeumannHeatCoeff ω t a)
        = Real.sqrt (coeffL2Energy (shiftedNeumannHeatCoeff ω t a)) := rfl
    _ ≤ Real.sqrt
          ((Real.exp (-(ω * t))) ^ 2 * coeffL2Energy a) := hsqrt
    _ = Real.exp (-(ω * t)) * coeffL2Norm a := by
          rw [Real.sqrt_mul (sq_nonneg (Real.exp (-(ω * t))))]
          rw [Real.sqrt_sq hfactor_nonneg]
          rfl

/-- Pointwise first-mode decay for zero-mode-free coefficients under the
unshifted Neumann heat semigroup. -/
theorem unshiftedNeumannHeatCoeff_sq_le_firstNonzero_of_zeroMode
    {t : ℝ} (ht : 0 ≤ t) {a : ℕ → ℂ} (ha0 : a 0 = 0) (n : ℕ) :
    ‖shiftedNeumannHeatCoeff 0 t a n‖ ^ 2 ≤
      (Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t))) ^ 2 *
        ‖a n‖ ^ 2 := by
  by_cases hn : n = 0
  · subst n
    simp [shiftedNeumannHeatCoeff, ha0]
  · set r := shiftedNeumannEigenvalue 0 n with hrdef
    have hge : unitIntervalNeumannSpectrum.firstNonzero ≤ r := by
      have H := unitIntervalNeumannSpectrum_hasNeumannSpectrum
      have hle := H.firstNonzero_le_eigenvalue n hn
      simpa [hrdef, shiftedNeumannEigenvalue] using hle
    have hmul :
        -(r * t) ≤ -(unitIntervalNeumannSpectrum.firstNonzero * t) := by
      have hrt :
          unitIntervalNeumannSpectrum.firstNonzero * t ≤ r * t :=
        mul_le_mul_of_nonneg_right hge ht
      linarith
    have hexp_le :
        Real.exp (-(r * t)) ≤
          Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t)) :=
      Real.exp_le_exp.mpr hmul
    have hexp_nonneg : 0 ≤ Real.exp (-(r * t)) := Real.exp_nonneg _
    have hfirst_nonneg :
        0 ≤ Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t)) :=
      Real.exp_nonneg _
    have hnorm_nonneg : 0 ≤ ‖a n‖ := norm_nonneg _
    have hle :
        Real.exp (-(r * t)) * ‖a n‖ ≤
          Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t)) *
            ‖a n‖ :=
      mul_le_mul_of_nonneg_right hexp_le hnorm_nonneg
    calc
      ‖shiftedNeumannHeatCoeff 0 t a n‖ ^ 2
          =
            (Real.exp (-(r * t)) * ‖a n‖) ^ 2 := by
              rw [shiftedNeumannHeatCoeff, ← hrdef, norm_mul,
                Complex.norm_of_nonneg hexp_nonneg]
      _ ≤
            (Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t)) *
              ‖a n‖) ^ 2 := by
              exact
                (sq_le_sq₀
                  (mul_nonneg hexp_nonneg hnorm_nonneg)
                  (mul_nonneg hfirst_nonneg hnorm_nonneg)).mpr hle
      _ =
            (Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t))) ^ 2 *
              ‖a n‖ ^ 2 := by
              ring

/-- Coefficient `ℓ²` norm first-mode decay for zero-mode-free unshifted
Neumann heat. -/
theorem unshiftedNeumannHeatCoeff_l2_norm_firstNonzero_of_zeroMode
    {t : ℝ} (ht : 0 ≤ t) {a : ℕ → ℂ}
    (ha : Summable fun n : ℕ => ‖a n‖ ^ 2) (ha0 : a 0 = 0) :
    coeffL2Norm (shiftedNeumannHeatCoeff 0 t a) ≤
      Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t)) *
        coeffL2Norm a := by
  have hs :
      Summable fun n : ℕ => ‖shiftedNeumannHeatCoeff 0 t a n‖ ^ 2 := by
    apply Summable.of_nonneg_of_le
      (fun n => sq_nonneg _)
      ?_
      (ha.mul_left
        ((Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t))) ^ 2))
    intro n
    exact unshiftedNeumannHeatCoeff_sq_le_firstNonzero_of_zeroMode
      ht ha0 n
  have hmajor :
      Summable fun n : ℕ =>
        (Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t))) ^ 2 *
          ‖a n‖ ^ 2 :=
    ha.mul_left
      ((Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t))) ^ 2)
  have hle :
      ∀ n : ℕ,
        ‖shiftedNeumannHeatCoeff 0 t a n‖ ^ 2 ≤
          (Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t))) ^ 2 *
            ‖a n‖ ^ 2 :=
    unshiftedNeumannHeatCoeff_sq_le_firstNonzero_of_zeroMode ht ha0
  have henergy :
      coeffL2Energy (shiftedNeumannHeatCoeff 0 t a) ≤
        (Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t))) ^ 2 *
          coeffL2Energy a := by
    have htsum := hs.tsum_le_tsum hle hmajor
    simpa [coeffL2Energy, ha.tsum_mul_left] using htsum
  have hsqrt := Real.sqrt_le_sqrt henergy
  have hfactor_nonneg :
      0 ≤ Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t)) :=
    Real.exp_nonneg _
  calc
    coeffL2Norm (shiftedNeumannHeatCoeff 0 t a)
        = Real.sqrt (coeffL2Energy (shiftedNeumannHeatCoeff 0 t a)) := rfl
    _ ≤ Real.sqrt
          ((Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t))) ^ 2 *
            coeffL2Energy a) := hsqrt
    _ =
          Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t)) *
            coeffL2Norm a := by
          rw [Real.sqrt_mul
            (sq_nonneg
              (Real.exp (-(unitIntervalNeumannSpectrum.firstNonzero * t))))]
          rw [Real.sqrt_sq hfactor_nonneg]
          rfl

/-! ### One theorem-shaped package for the concrete H3.1 subblock -/

/-- Nonnegativity of the shifted diagonal spectrum forces the shift itself to
be nonnegative, since the Neumann spectrum has zero as its first eigenvalue. -/
lemma shiftedNeumannShift_nonneg_of_spectrum_nonneg
    {ω : ℝ} (hspectrum : ∀ n : ℕ, 0 ≤ shiftedNeumannEigenvalue ω n) :
    0 ≤ ω := by
  have h0 := hspectrum 0
  unfold shiftedNeumannEigenvalue at h0
  rw [unitIntervalNeumannSpectrum_hasNeumannSpectrum.zero_eigenvalue] at h0
  simpa using h0

/-- The concrete diagonal sectorial-resolvent certificate used in this file.

For the coefficient model, the missing abstract Mathlib bridge is isolated to
this package: it records the right-half-plane resolvent estimate and the
accretive diagonal spectrum needed by the heat multiplier proofs below.
-/
structure ShiftedNeumannSectorialResolventCertificate (ω : ℝ) where
  eigenvalue_nonneg :
    ∀ n : ℕ, 0 ≤ shiftedNeumannEigenvalue ω n
  resolvent_norm_estimate :
    ∀ z : ℂ, z ≠ 0 → 0 ≤ z.re →
      ∀ a : ℕ → ℂ, Summable (fun n : ℕ => ‖a n‖ ^ 2) →
        coeffL2Norm (shiftedNeumannResolventCoeff ω z a) ≤
          ((1 : ℝ) / ‖z‖) * coeffL2Norm a

/-- Concrete coefficient version of the sectorial-generation subblock.

It includes the previously proved sector resolvent estimate, the complex-time
semigroup law, coefficientwise analyticity, the right-half-plane `ℓ²`
boundedness, and the smoothing estimate `‖A e^{-tA}‖ ≤ 1/t`.
-/
structure ShiftedNeumannCoefficientAnalyticSemigroup (ω : ℝ) where
  resolvent_norm_estimate :
    ∀ z : ℂ, z ≠ 0 → 0 ≤ z.re →
      ∀ a : ℕ → ℂ, Summable (fun n : ℕ => ‖a n‖ ^ 2) →
        coeffL2Norm (shiftedNeumannResolventCoeff ω z a) ≤
          ((1 : ℝ) / ‖z‖) * coeffL2Norm a
  zero :
    ∀ a : ℕ → ℂ,
      shiftedNeumannAnalyticHeatCoeff ω 0 a = a
  add :
    ∀ (z w : ℂ) (a : ℕ → ℂ),
      shiftedNeumannAnalyticHeatCoeff ω (z + w) a =
        shiftedNeumannAnalyticHeatCoeff ω z
          (shiftedNeumannAnalyticHeatCoeff ω w a)
  analytic_coeff :
    ∀ (a : ℕ → ℂ) (n : ℕ) (z : ℂ),
      AnalyticAt ℂ
        (fun ζ : ℂ => shiftedNeumannAnalyticHeatCoeff ω ζ a n) z
  rightHalfPlane_l2_bound :
    ∀ z : ℂ, 0 ≤ z.re →
      ∀ a : ℕ → ℂ, Summable (fun n : ℕ => ‖a n‖ ^ 2) →
        coeffL2Norm (shiftedNeumannAnalyticHeatCoeff ω z a) ≤
          coeffL2Norm a
  generator_l2_bound :
    ∀ t : ℝ, 0 < t →
      ∀ a : ℕ → ℂ, Summable (fun n : ℕ => ‖a n‖ ^ 2) →
        coeffL2Norm (shiftedNeumannGeneratorHeatCoeff ω t a) ≤
          ((1 : ℝ) / t) * coeffL2Norm a
  spectral_bound_decay :
    ∀ t : ℝ, 0 ≤ t →
      ∀ a : ℕ → ℂ, Summable (fun n : ℕ => ‖a n‖ ^ 2) →
        coeffL2Norm (shiftedNeumannHeatCoeff ω t a) ≤
          Real.exp (-(ω * t)) * coeffL2Norm a

/-- The diagonal sectorial-resolvent certificate generates the concrete
coefficient analytic semigroup package.

This is the explicit H3.1 chain proved here: the sector resolvent estimate is
threaded through the generation certificate, and the unit-interval spectral
nonnegativity supplies the multiplier bounds for `e^{-zA}` and `A e^{-tA}`.
-/
theorem ShiftedNeumannSectorialResolventCertificate.generates
    {ω : ℝ} (cert : ShiftedNeumannSectorialResolventCertificate ω) :
    ShiftedNeumannCoefficientAnalyticSemigroup ω where
  resolvent_norm_estimate := cert.resolvent_norm_estimate
  zero := shiftedNeumannAnalyticHeatCoeff_zero ω
  add := shiftedNeumannAnalyticHeatCoeff_add ω
  analytic_coeff := shiftedNeumannAnalyticHeatCoeff_analyticAt ω
  rightHalfPlane_l2_bound := by
    intro z hz a ha
    have hω : 0 ≤ ω :=
      shiftedNeumannShift_nonneg_of_spectrum_nonneg cert.eigenvalue_nonneg
    exact shiftedNeumannAnalyticHeatCoeff_l2_norm_le hω hz ha
  generator_l2_bound := by
    intro t ht a ha
    have hω : 0 ≤ ω :=
      shiftedNeumannShift_nonneg_of_spectrum_nonneg cert.eigenvalue_nonneg
    exact shiftedNeumannGeneratorHeatCoeff_l2_norm_le hω ht ha
  spectral_bound_decay := by
    intro t ht a ha
    exact shiftedNeumannHeatCoeff_l2_norm_decay ht ha

/-- The unit-interval Neumann spectrum supplies the diagonal sectorial
resolvent certificate for `A = -Δ_N + ω`. -/
theorem unitInterval_shiftedNeumann_sectorialResolventCertificate
    {ω : ℝ} (hω : 0 ≤ ω) :
    ShiftedNeumannSectorialResolventCertificate ω where
  eigenvalue_nonneg := shiftedNeumannEigenvalue_nonneg hω
  resolvent_norm_estimate :=
    intervalDomain_shiftedNeumannResolvent_l2_norm_estimate hω

/-- Unit-interval Neumann coefficient sectorial generation package for
`A = -Δ_N + ω`, with shift `ω ≥ 0`. -/
theorem unitInterval_shiftedNeumann_coefficient_analyticSemigroup
    {ω : ℝ} (hω : 0 ≤ ω) :
    ShiftedNeumannCoefficientAnalyticSemigroup ω :=
  (unitInterval_shiftedNeumann_sectorialResolventCertificate hω).generates

end ShenWork.PDE.AnalyticSemigroupGen
