import ShenWork.Paper3.IntervalDomainPersistenceGeneralMRegularity
import ShenWork.Paper3.IntervalDomainPersistenceGeneralMGrowthNearArgmin
import ShenWork.Paper3.IntervalDomainPersistenceGeneralMSlopeBounds
import ShenWork.Paper3.IntervalDomainPersistenceDiniBridge

open Filter Topology
open ShenWork.IntervalDomain
open ShenWork.Paper2.IntervalDomainMMinPersistence

namespace ShenWork.Paper3

noncomputable section

/-- Ceiling-conditioned lower-right Dini inequality for the faithful all-sign
general-`m` spatial minimum, retaining the positive linear reaction. -/
theorem intervalDomainM_generalMGrowthSpatialMinimumDini_at
    {p : CM2Params} {u v : ℝ → intervalDomain.Point → ℝ}
    (hm : 1 ≤ p.m)
    (hsol : PositiveGlobalBoundedSolution intervalDomainM p u v)
    {t M : ℝ} (ht : t ∈ Set.Ioi (0 : ℝ)) (hM : 0 ≤ M)
    (hu_bd : ∀ y, |intervalDomainLift (u t) y| ≤ M) :
    generalMMinGrowthRate p M * intervalDomainSpatialMin u t ≤
      compactMinLowerRightDini (intervalDomainSpatialMin u) t := by
  exact lowerRightDini_min_ge_of_near_argmin_ft_lower
    (intervalDomainM_generalM_compactMinFamily (p := p) (v := v) hsol)
    (intervalDomainM_generalM_uniformRightDerivLower hsol t ht)
    (intervalDomainM_generalM_uniformTimeContinuity hsol t ht)
    (intervalDomainM_generalM_growth_nearArgmin_ft_lower hm hsol
      t ht M hM hu_bd)
    (intervalDomainM_spatialMin_slope_isCoboundedUnder hsol t ht)
    (intervalDomainM_spatialMin_slope_isBoundedUnder hsol t ht)

/-- On any positive-time set carrying a common slice ceiling, the faithful
minimum satisfies the native frequently-small-slope Dini interface with the
linear vector field generated by the ceiling-dependent growth rate. -/
theorem intervalDomainM_generalMGrowthRightLowerDiniGE_on
    {p : CM2Params} {u v : ℝ → intervalDomain.Point → ℝ}
    (hm : 1 ≤ p.m)
    (hsol : PositiveGlobalBoundedSolution intervalDomainM p u v)
    {I : Set ℝ} {M : ℝ} (hI : I ⊆ Set.Ioi (0 : ℝ)) (hM : 0 ≤ M)
    (hu_bd : ∀ t ∈ I, ∀ y, |intervalDomainLift (u t) y| ≤ M) :
    RightLowerDiniGE (intervalDomainSpatialMin u)
      (fun z => generalMMinGrowthRate p M * z) I := by
  apply rightLowerDiniGE_of_compactMinLowerRightDini
  · intro t ht
    exact intervalDomainM_generalMGrowthSpatialMinimumDini_at hm hsol
      (hI ht) hM (hu_bd t ht)
  · intro t ht
    exact intervalDomainM_spatialMin_slope_isBoundedUnder hsol t (hI ht)

end

end ShenWork.Paper3

#print axioms
  ShenWork.Paper3.intervalDomainM_generalMGrowthSpatialMinimumDini_at
#print axioms ShenWork.Paper3.intervalDomainM_generalMGrowthRightLowerDiniGE_on
